stm32duino/Arduino_Core_STM32

cores/arduino/stm32/uart.c
Issue #16 
We now check if data as been correctly sent when printf() is used. printf() was in conflict with Serial.print() because it uses uart in polling mode and Serial uses uart in IT mode.
printf() function should be used only for debug purpose inside core.
=> Removed conflict between printf & Serial.print

cores/arduino/stm32/clock.c, cores/arduino/stm32/spi_com.c, libraries/SPI/SPI.cpp, libraries/SPI/SPI.h
Fix #11:
- SPI constructor modified. SS pin should be set only if hardware NSS pin is required.
- Hardware NSS pin can be enabled. If NSS enabled, software CS is disabled.
See microcontroller documentation for hardware NSS pin available.
=> Fixed issue #11: SPI constructors and SS pin usage modified

libraries/SPI/SPI.cpp
When the SPI device is configured for MSB first, the 16 bit data being
sent and received on the SPI bus has the bytes swapped if the
SPI.transfer16() method is used. Swapping the bytes before and after the
call to spi_transfer() fixes the problem.
Tested using an AS5147P magnetic encoder spi device. Before the fix, saw
frame errors due to the bytes being swapped, when the same unmodified
code worked perfectly on an AVR based SparkFun RedBoard.
Signed-off-by: Theodore A. Roth <troth@openavr.org>
=> Fix SPI transfer16

cores/arduino/HardwareSerial.cpp, cores/arduino/HardwareSerial.h
Fix #50
Arduino defined several configs (data, parity and stop bits) values
for Serial.begin(speed, config)
See: https://www.arduino.cc/en/Serial/Begin
Below configs could not be supported by STM32 as minimum
wordlength (data + parity) is UART_WORDLENGTH_7B (7 bits).
SERIAL_5N1
SERIAL_5N2
SERIAL_5E1
SERIAL_5E2
SERIAL_5O1
SERIAL_5O2
SERIAL_6N1
SERIAL_6N2
=> Fix Serial config

boards.txt, cores/arduino/stm32/usb_interface.h, cores/arduino/utils.h, libraries/Keyboard/src/Keyboard.h, libraries/Mouse/src/Mouse.h, platform.txt, variants/DISCO_F407VG/usb/usbd_desc.c, variants/NUCLEO_F429ZI/usb/usbd_desc.c
With this pull User is now able to enable other Serial Instance or USB thanks the Tools Menu.
=> Add menu to enable Serial instances and USB interface

cores/arduino/stm32/stm32_eeprom.c
Patch following a problem encountered in #56. 
Hard coded addresses has been replaced with more generic code definition.
@fpistm the F7 and F2 need to be tested! Other are OK.
=> Replaced hard coded EEPROM base address with generic code

cores/arduino/HardwareSerial.cpp
In my opinion, there is a potential bug when a character equal to -1 is sent by serial port; in this case according the current implementation the following character in the queue is not transmitted. For this reason I propose to simplify _tx_complete_irq implementation just returning 0 if we still have characters to be transmitted, -1 otherwise.
=> Fix possible issue on serial ports

cores/arduino/stm32/twi.c, libraries/Wire/Wire.cpp, libraries/Wire/examples/master_reader_writer/master_reader_writer.ino, libraries/Wire/examples/slave_sender_receiver/slave_sender_receiver.ino
The new STM32F1xx HAL release allow to remove specific set up for STM32F1 boards inside I2C core and library.
The specific examples for F1 has been reworked too.
=> I2C update following new STM32F1 HAL release

cores/arduino/pins_arduino.h, cores/arduino/wiring_constants.h
Add several macro for compatibily (register access)
Added:
```
analogInPinToBit
portOutputRegister
portInputRegister
portSetRegister
portClearRegister
portConfigRegister
portModeRegister
_BV
cbi
sbi
```
=> Missing compatibility

cores/arduino/stm32/interrupt.c
Reduce gpio_irq_conf array of 64 bytes.
Pin is the index.
=> Remove unused .pin field of gpio_irq_conf_str structure

cores/arduino/board.h, cores/arduino/main.cpp, cores/arduino/stm32/core_callback.c, cores/arduino/stm32/core_callback.h
The Ethernet library is no more linked to the core.
See STM32Ethernet [PR](https://github.com/stm32duino/STM32Ethernet/pull/2).
=> Remove Ethernet library dependency

boards.txt, platform.txt
=> Shorten options names to avoid issue with aggressively cache compiled core

cores/arduino/stm32/timer.c, cores/arduino/stm32/timer.h
=> Add missing timer IRQHandler and fix wrong timer IRQHandler

cores/arduino/stm32/spi_com.c, cores/arduino/stm32/twi.c
If we use a dynamic instanciation, the state is not well
initialized. This can ends with a blocking or strange
behaviour.
=> initialize state before calling HAL_XXX_Init for SPI and I2C

cores/arduino/stm32/twi.c
I faced an issue while coding a demo for L475 IoT board that use several sensors on i2c2 and BTLE on SPI3. With the actual polling mode for I2C, the transfers can be disturbed by SPI. 
Commit message : 
Switch from polling mode to IT mode for I2C transfers.
For example, this is needed if we want to use SPI and
I2C in the same time.
=> Use interrupt mode for I2C transfers

cores/arduino/stm32/stm32_def.h, cores/arduino/stm32/uart.c, cores/arduino/stm32/uart.h
=> Added missing U(S)ART peripherals management

boards.txt
Example for Nucleo-L476RG:
**No FPU (SoftFP)**
Sketch uses 25940 bytes (2%) of program storage space. Maximum is 1048576 bytes.
Results:
```
time for 1 mio. plus calculations in s: 0.77
time for 1 mio. minus calculations in s: 0.79
time for 1 mio. multiplications in s: 0.51
time for 1 mio. divisions in s: 1.96
```
**FPU enabled (SP):**
Sketch uses 24772 bytes (2%) of program storage space. Maximum is 1048576 bytes.
Results:
```
time for 1 mio. plus calculations in s: 0.05
time for 1 mio. minus calculations in s: 0.05
time for 1 mio. multiplications in s: 0.06
time for 1 mio. divisions in s: 0.19
```
=> Enabled FPU Single Precision (SP)

variants/NUCLEO_F091RC/ldscript.ld, variants/NUCLEO_F303RE/ldscript.ld, variants/NUCLEO_L053R8/ldscript.ld, variants/NUCLEO_L476RG/ldscript.ld
Ex: 0x20001FFF is the last valid byte address of RAM for NUCLEO_L053R8,
but the error is that it is not aligned and there is no reason to put
this value as stack pointer.
When Cortex-M push something in the stack, it first decrement the stack
pointer and then writes at the new address.
So using initial value 0x20002000 is ok.
The first word will be at address _estack-4, in RAM
=> Some linker script has the stack pointer __NOT__ 8-byte aligned

libraries/SPI/src/SPI.cpp
SPI library patched to remove overrun of an array causing random behaviour.
There is no problem with UART layer.
The [WiFi library](https://github.com/stm32duino/WiFi-ISM43362-M3G-L44/pull/1) is OK now.
=> Fix SPI memory leak

cores/arduino/HardwareSerial.cpp, cores/arduino/stm32/uart.c, cores/arduino/stm32/uart.h
In case of several Serial instances, a global variable was used for all received char.
=> Remove global variable used for uart Rx

cores/arduino/stm32/spi_com.c
Hi all,
I found a potential issue in the SPI library when the SPI instance is generated using dynamic allocation. In particular the "NSSPMode" field of the “Init” structure of the "SPI_HandleTypeDef" could be randomly initialized and it could cause troubles in the "HAL_SPI_Init". In order to avoid that we need to correctly initialized this field inside the spi_init.
I also fixed some compilation warnings (for Nucleo-L476RG) due to a misalignment in the .text section of the Linker Script. Probably this issue affects other platforms too.
Best Regards,
Carlo
=> Fix issue on SPI for F0, F3, F7 and L4 platforms

cores/arduino/stm32/stm32_def.h, cores/arduino/stm32/twi.c, cores/arduino/stm32/twi.h
=> I2C IT mode

cores/arduino/main.cpp, cores/arduino/stm32/core_callback.c, cores/arduino/stm32/core_callback.h
STM32Ethernet do not use anymore this feature.
Disabled it to avoid unuseful call in the main while{}.
Define CORE_CALLBACK allow to enable it.
=> Disabled Core callback feature

variants/DISCO_F100RB/ldscript.ld, variants/DISCO_F407VG/ldscript.ld, variants/DISCO_F746NG/ldscript.ld, variants/NUCLEO_F030R8/ldscript.ld, variants/NUCLEO_F091RC/ldscript.ld, variants/NUCLEO_F103RB/ldscript.ld, variants/NUCLEO_F207ZG/ldscript.ld, variants/NUCLEO_F302R8/ldscript.ld, variants/NUCLEO_F303K8/ldscript.ld, variants/NUCLEO_F401RE/ldscript.ld, variants/NUCLEO_F411RE/ldscript.ld, variants/NUCLEO_F429ZI/ldscript.ld, variants/NUCLEO_L053R8/ldscript.ld, variants/NUCLEO_L152RE/ldscript.ld, variants/NUCLEO_L432KC/ldscript.ld, variants/NUCLEO_L476RG/ldscript.ld
Wait last CI build before merge.
=> Fixed warning: changing start of section .text by x bytes

cores/arduino/stm32/twi.c
Hi all,
this patch should fix [this](https://github.com/stm32duino/Arduino_Core_STM32/issues/153) bug. I successfully tested it with Nucleo-F401RE and X-NUCLEO-NFC01A1 and X-NUCLEO-NFC04A1. In order to fix it, I took inspiration by Cube HAL examples for I2C in IT mode. Please, let me know if it works also on your side. 
Best Regards,
Carlo
=> Fix I2C bug for F4 platforms in IT mode

README.md, boards.txt, variants/DISCO_L072CZ_LRWAN1/PeripheralPins.c, variants/DISCO_L072CZ_LRWAN1/README.md, variants/DISCO_L072CZ_LRWAN1/ldscript.ld, variants/DISCO_L072CZ_LRWAN1/stm32l0xx_hal_conf.h, variants/DISCO_L072CZ_LRWAN1/variant.cpp, variants/DISCO_L072CZ_LRWAN1/variant.h
Thanks to @knielsen
Based on #151 
Some cosmetic update. (squash,...)
=> Discovery L072CZ-LRWAN1 support

cores/arduino/WInterrupts.cpp, cores/arduino/WInterrupts.h, cores/arduino/board.h, cores/arduino/stm32/interrupt.cpp, cores/arduino/stm32/interrupt.h, cores/arduino/wiring.h
The function attachInterrupt now also accept std:function<void(void)> in order to bind object method to an interrupt.
=> Added ability to bind std:function on interrupts

cores/arduino/HardwareSerial.cpp, cores/arduino/stm32/uart.c, variants/board_template/variant.h
If the debug UART is not initialized by a Serial instance, init it at 9600 (8N1) by default.
Else use the config done by the Serial instance.
Those values could be redefined in the variant.h
DEBUG_UART could be redefined to print on another instance than 'Serial'
`#define DEBUG_UART              ((USART_TypeDef *) U(S)ARTX) // ex: USART3`
DEBUG_UART baudrate, default: 9600 if not defined
`#define DEBUG_UART_BAUDRATE     115200`
DEBUG_UART Tx pin name, default: the first one found in PinMap_UART_TX for DEBUG_UART
`#define DEBUG_PINNAME_TX        PX_n // PinName used for TX`
=> Enhance DEBUG_UART feature (used by printf)

cores/arduino/pins_arduino.h, cores/arduino/stm32/stm32_def.c, cores/arduino/stm32/stm32_def.h
Allow to use the SystemClock_Config() from STM32CubeMX without any change.
It could be redefined by user at sketch level (weak)
extern "C" void _Error_Handler(const char * file, int line)
{
...
}
Fix #66
=> Added _Error_Handler(const char *, int)

libraries/SPI/README.md, libraries/SPI/src/SPI.cpp, libraries/SPI/src/SPI.h
Try to improve the clarity of the SPI library code after the feedback #157
=> Improve SPI library code understanding

cores/arduino/avr/pgmspace.h
Based on Paul Stoffregen work on Teensy 3 (http://pjrc.com)
Fix #163
=> Updated pgmspace.h

cores/arduino/pins_arduino_var.h, variants/DISCO_F100RB/variant.h, variants/DISCO_F407VG/variant.h, variants/DISCO_F746NG/variant.h, variants/DISCO_L072CZ_LRWAN1/variant.h, variants/DISCO_L475VG_IOT/variant.h, variants/NUCLEO_F030R8/variant.h, variants/NUCLEO_F091RC/variant.h, variants/NUCLEO_F103RB/variant.h, variants/NUCLEO_F207ZG/variant.h, variants/NUCLEO_F302R8/variant.h, variants/NUCLEO_F303K8/variant.h, variants/NUCLEO_F303RE/variant.h, variants/NUCLEO_F401RE/variant.h, variants/NUCLEO_F411RE/variant.h, variants/NUCLEO_F429ZI/variant.h, variants/NUCLEO_F446RE/variant.h, variants/NUCLEO_L053R8/variant.h, variants/NUCLEO_L152RE/variant.h, variants/NUCLEO_L432KC/variant.h, variants/NUCLEO_L476RG/variant.h, variants/board_template/variant.h
- Common definitions are moved to pins_arduino_var.h.
They could be redefined in variant.h if needed.
- Removed *UART_EMUL* definitions as it is needed to be reworked in SoftwareSerial library.
- Pin number over D15 replaced by pin name (more relevant)
- Fixed some typos
=> Clean variants files

cores/arduino/stm32/analog.c
Fix #168
Last STM32L4xx HAL Drivers update change ADC init (using LL).
Some ADC_ChannelConfTypeDef fields were missing. Mainly SingleDiff.
=> Fixed ADC read value

platform.txt
It is now possible to customize some core definitions
or gcc options thanks a file named "`build_opt.h"`
in the sketch directory. (using @file gcc option)
User can add it thanks the Arduino IDE in a tab to easily customize the core options.
That's why '.h' extension is used as IDE allows only those one: ino, h, hpp, c, cpp, pde.
Note: file is automatically copied in the `{build.path}/sketch/` directory
Example of file content to change F_CPU value:
`-UF_CPU -DF_CPU=72000000UL`
If the file does not exist an empty one is created in the `{build.path}/sketch/` directory.
Fix #41
=> Build option

.gitignore
You can keep local platform configurations in the `boards.local.txt` and `platform.local.txt`
For example if you want to use -std=c++17 you can add this file to the root:
platform.local.txt:
`compiler.cpp.flags={compiler.extra_flags} -c {build.flags.optimize} {compiler.warning_flags} -std=c++17 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD {compiler.stm.extra_include}`
(using a g++ 7.2 cross compiler)
This PR simply adds those files to .gitignore so that your private/local changes won't accidentally be included in any commit.
=> Added .DS_Store, boards.local.txt and platform.local.txt to .gitignore

libraries/Servo/examples/fs90r/fs90r.ino
This example shows how to use servo library to drive
a continuous rotation servo motor. It also shows how
to use attach with min and max values.
=> Add fs90r example to servo library

libraries/SPI/keywords.txt, libraries/SPI/src/SPI.h, libraries/Wire/keywords.txt, libraries/Wire/src/Wire.h
Example to change pins used by Wire instance (by default use defined SDA/SCL ):
```
Wire.setSDA(A4);
Wire.setSCL(PC2);
Wire.begin();
```
Example to change pins used by SPI instance (by default use defined MISO/MOSI/SCK):
```
SPI.setMOSI(22);
SPI.setMISO(PA3);
SPI.begin();
```
=> Added setXXX methods to change used pins of an instance

cores/arduino/HardwareSerial.cpp, cores/arduino/HardwareSerial.h
Allow to instantiate HardwareSerial with pin number.
Both lines are the same:
```
HardwareSerial SerialLora(PA_1, PA_0); // PinNames
HardwareSerial SerialLora(PA1, PA0); // Pin number
```
=> Added new HardwareSerial constructor using pin number

cores/arduino/stm32/clock.c
Test:
```
for( uint32_t i = 0; i<2000; i++) { 
start_us= micros();
delayMicroseconds(i);
end_us = micros();
}
```
_diff_ = `end_us - start_us` is the difference btw the requested delay and the measured one with micros()
_old_ = number of the same difference in the 2000 iteration  for the previous implementation
_new_ = number of the same difference in the 2000 iteration  for this PR implementation
**Nucleo-F103RB**
| diff (ms) | old | new |
| :---: | :---: | :---: |
| 0 |  0 | 4 |  
| 1 | 0 | 149 |  
| 2 | 633 | 1842 |  
| 3 | 1015 | 5 |  
| 4 | 348 | 0 |  
| 5 | 3 | 0 |  
**Discovery L475VG IOT**
| diff (ms) | old | new |
| :---: | :---: | :---: |
| 0 |  148 | 699 |  
| 1 | 811 | 1030 |  
| 2 | 1038 | 271 |  
| 3 | 3 | 0 |  
| 4 | 0 | 0 |  
| 5 | 0 | 0 |
=> Improves micros() accuracy using SysTick COUNTFLAG

cores/arduino/new.cpp, platform.txt
Requires a recent arm toolchain to be used.
Based on PR #191 proposed by @xloem
Updated using @lacklustrlabs suggestion:
Make the '-std=gnu++14' flag a variable using 'compiler.cpp.flags' variable.
This way it is easy to change the -std setting in platform.local.txt without
overriding anything else.
platform.local.txt:
compiler.cpp.std=gnu++11
Signed-off-by: Frederic Pillon <frederic.pillon@st.com>
=> Update c++ compilation standard to 2014 from 2011

cores/arduino/pins_arduino_var.h, variants/DISCO_F100RB/variant.h, variants/DISCO_F407VG/variant.h, variants/DISCO_F746NG/variant.h, variants/DISCO_L072CZ_LRWAN1/variant.h, variants/DISCO_L475VG_IOT/variant.h, variants/NUCLEO_F030R8/variant.h, variants/NUCLEO_F091RC/variant.h, variants/NUCLEO_F103RB/variant.h, variants/NUCLEO_F207ZG/variant.h, variants/NUCLEO_F302R8/variant.h, variants/NUCLEO_F303K8/variant.h, variants/NUCLEO_F303RE/variant.h, variants/NUCLEO_F401RE/variant.h, variants/NUCLEO_F411RE/variant.h, variants/NUCLEO_F429ZI/variant.h, variants/NUCLEO_F446RE/variant.h, variants/NUCLEO_L031K6/variant.h, variants/NUCLEO_L053R8/variant.h, variants/NUCLEO_L152RE/variant.h, variants/NUCLEO_L432KC/variant.h, variants/NUCLEO_L476RG/variant.h, variants/board_template/variant.h
It turned out that I needed the fix of #140 for a pet project of mine. 
So here are the changes I made.
I've compiled every board with this .ino:
```
#if NUM_DIGITAL_PINS > 4
#else
#error "NUM_DIGITAL_PINS not fixed"
#endif
#if NUM_ANALOG_INPUTS > 1
#else
#error "NUM_ANALOG_INPUTS not fixed"
#endif
void setup() {
}
void loop() {
} 
```
=> Assigning literal values to NUM_DIGITAL_PINS and NUM_ANALOG_INPUTS

cores/arduino/pins_arduino.h, variants/board_template/variant.h
To be able to use `analogRead(A0)` and `analogRead(0)`, A0 pin value
must be greater than or equal to `NUM_ANALOG_INPUTS`.
Ex:
If `NUM_ANALOG_INPUTS` was 6 (A0 to A5) and A0 was defined to 3 (D3),
`analogRead(A0)` would read A3 instead of A0.
=> Avoid to have first analog pin value (A0) lesser than NUM_ANALOG_INPUTS

cores/arduino/stm32/twi.c, libraries/Wire/src/Wire.cpp, libraries/Wire/src/Wire.h
=> Fix I2C slave issue

platform.txt
I had a conflict with the version of the ARM GCC used by the official Arduino SAMD core, this changes specifies the version of GCC in the path, so that the arduino-builder/IDE can select the right version.
=> Specify the ARM GCC version in platforms.txt

boards.txt
Since 5b811b459872a9474470987654d3d6fe57c5c7eb, those lines are useless
=> Remove useless build.flags for default optimization

libraries/IWatchdog/README.md, libraries/IWatchdog/examples/IWDG_Button/IWDG_Button.ino, libraries/IWatchdog/keywords.txt, libraries/IWatchdog/library.properties, libraries/IWatchdog/src/IWatchdog.cpp, libraries/IWatchdog/src/IWatchdog.h
Based on first implementation (#234) from @ghent360.
Use LL instead of HAL (no need to enable the HAL_IWDG_MODULE_ENABLED).
Applicable to all STM32 series.
Window mode is available for STM32 series which support the feature.
API  added to know if the system has resumed from IWDG reset.
Timeout range increase using LSI_VALUE of the target.
=> Add built-in IWatchdog library to expose the IWDG component.

cores/arduino/stm32/twi.c
##Description
For STM32 families that have a DutyCycle init parameter, we need to
select the Fast Mode dedicated configuration which will set the
fast mode bit in CCR register.
Fixes #203 
so #203 can be removed from the list to be addressed in #217 
Tested on NUCLEO_L152RE and NUCLEO_F429ZI with eepromTest example from extEEPROM library.
=> Configure I2C Fast Mode when I2C freq is more than 100kHz

cores/arduino/stm32/stm32_eeprom.c, cores/arduino/stm32/stm32_eeprom.h
Split of #302 from @hasenbanck
=> [#302 review]Rework eeprom emulation for buffered access

libraries/EEPROM/library.properties, libraries/EEPROM/src/EEPROM.h
* Update to follow library specification    
https://github.com/arduino/arduino/wiki/arduino-ide-1.5:-library-specification
* Fix warnings    
type qualifiers ignored on function return type [-Wignored-qualifiers]
=> Update EEPROM library

cores/arduino/Stream.cpp, cores/arduino/Stream.h
I guess nobody at Arduino ever bothers to compile with full warnings enabled, which in fact is not the default compiler setting.
=> Fix input string const-ness to avoid warnings with literal strings

CI/build/arduino-builder.py
Since Arduino 1.8.6, it is possible to get the version using the CLI.
Use:
```
-core-api-version string
version of core APIs (used to populate ARDUINO #define) (default "10600")
```
instead of:
```
-ide-version string
[deprecated] use 'core-api-version' instead (default "10600")
```
=> [CI] Use real core-api-version if possible

cores/arduino/stm32/stm32_eeprom.c, cores/arduino/stm32/stm32_eeprom.h
With this PR, user is now able to customize which part of the FLASH to used for EEPROM emulation.
Example to  use the  sector 3 of the DISCO F746NG:
```
#define FLASH_DATA_SECTOR 3
#define FLASH_BASE_ADDRESS  0x08018000
```
=>  [EEPROM] Allow FLASH definition to be redefined

cores/arduino/stm32/rtc.c, cores/arduino/stm32/rtc.h
Add `HOUR_` prefix.
Require by STM32RTC library higher than 1.1.0
See https://github.com/stm32duino/STM32RTC/pull/12
=> Change hourAM_PM_t enum member name

boards.txt, cores/arduino/syscalls.c, libraries/Wire/src/Wire.cpp, variants/NUCLEO_L432KC/ldscript.ld
This PR include:
* Fix possible issue with realloc usage
* Define `_sbrk` as weak (Required by https://github.com/stm32duino/STM32FreeRTOS/issues/9)
* Avoid user heap to override the minimum stack size (Fix #307)
* Fix Nucleo-L432KC and Nucleo-L476RG SRAM usage
=> Enhance memory management

cores/arduino/WCharacter.h, cores/arduino/wiring_constants.h, libraries/Servo/src/stm32/Servo.cpp
boolean type now marked as deprecated
https://github.com/arduino/Arduino/issues/4673
=> Replace boolean with standard bool

cores/arduino/utils.h, cores/arduino/wiring.h
Include utils.h manually will provide them
Note: `str()` and `xstr()` are now capitalized.
Fix #389 
@matthijskooijman : any comment are welcome ;)
=> Do not provide some default macro's

cores/arduino/stm32/stm32_eeprom.c, cores/arduino/stm32/stm32_eeprom.h, libraries/EEPROM/src/EEPROM.h
E2END is the last valid EEPROM address.
Fix #396
=> [EEPROM] Wrong E2END definition

cores/arduino/Udp.h
This was needed to use ArduinoMNS
it was tested on nucleo-f767zi
[Sandeep Mistry]
Add virtual beginMulticast(...) stub to UDP class
Change-Id: I7cb92be0c88d350408ecc21f1662299b0721856a
Origin: https://github.com/arduino/ArduinoCore-avr/commit/5a05bf01f4ffbe16670eb8d713688d059c3bd084
Author: Sandeep Mistry <s.mistry@arduino.cc>
Signed-off-by: Philippe Coval <p.coval@samsung.com>
=> udp: Add beginMulticast method

platform.txt
This allow to use switch in `ldscript.ld` file.
Would be useful for bootloader management.
Update:
Tested on Windows/Linux/Mac --> OK
Tested with Sloeber (to check if prelink is well handled). --> OK
=> Add preprocessing of linker script

variants/REMRAM_V1/variant.h
I thought I had set the I2C pins to the arduino compatible
values, but it seems I messed that up. This change will
set the defaults for the board variant RemRam V1.
=> Add I2C definition for RemRam V1

cores/arduino/stm32/usb/usbd_conf.c, cores/arduino/stm32/usb/usbd_if.c, cores/arduino/stm32/usb/usbd_if.h, variants/MAPLEMINI_F103CB/variant.h
Enumeration delay could be redefined using `USBD_ENUM_DELAY`
To disable re-enumeration define `USBD_REENUM_DISABLED`
Use `USB_DISC_PIN` if defined.
Tested with BluePill, MapleMini and Disco F746.
Any comments are welcome.
=> [USBD] Force re-enumeration

.gitignore, .travis.yml, CI/astyle/.astyleignore, CI/astyle/.astylerc, CI/astyle/.flake8, CI/astyle/astyle.py
AStyle will be used for coding style checking.
Only sources files (`*.h`, `*.hpp`, `*.c`, `*.cpp`) from the following lists will be check:
* cores
* libraries
* variants
`.astyleignore` file contains list of folder to ignore.
Hereafter the code style definition applied (`.astylerc`):
```bash
suffix=none
style=kr
-j
indent=spaces=2
convert-tabs
indent-classes
indent-switches
indent-cases
indent-col1-comments
unpad-paren
pad-header
pad-oper
align-pointer=name
align-reference=name
attach-namespaces
attach-classes
max-continuation-indent=120
keep-one-line-statements
```
Python script `astyle.py` is provided to ease use of AStyle:
```stdout
usage: astyle.py [-h] [-d <code style definition file>]
[-g | -b <branch name>] [-i <ignore file>]
[-p <astyle install path>] [-r <source root path>] …
```
=> Astyle deployement

cores/arduino/stm32/stm32_def.h
Based on Semantic Versioning 2.0.0 (https://semver.org/)
This will ease core dependencies.
* STM32_CORE_VERSION_MAJOR -> major version
* STM32_CORE_VERSION_MINOR -> minor version
* STM32_CORE_VERSION_PATCH -> patch version
* STM32_CORE_VERSION_EXTRA -> Extra label
with:
- 0: official release
- [1-9]: release candidate
- F[0-9]: development
* STM32_CORE_VERSION --> Full version number
=> Add STM32 core version

cores/arduino/stm32/usb/usbd_conf.c
=> True PMA correction

cores/arduino/board.h, cores/arduino/stm32/analog.c, cores/arduino/stm32/analog.h, cores/arduino/stm32/interrupt.cpp, cores/arduino/stm32/interrupt.h, cores/arduino/stm32/spi_com.c, cores/arduino/stm32/spi_com.h, cores/arduino/stm32/timer.c, cores/arduino/stm32/timer.h, cores/arduino/stm32/twi.c, cores/arduino/stm32/twi.h
=> Fix mis-placed extern "C" in board.h + some legacy comment cleanup

cores/arduino/board.h, cores/arduino/stm32/backup.h, cores/arduino/stm32/clock.c, cores/arduino/stm32/rtc.c, cores/arduino/stm32/rtc.h
=> [RTC] Avoid reset time after low power mode

cores/arduino/stm32/usb/cdc/usbd_cdc.c, cores/arduino/stm32/usb/cdc/usbd_cdc.h, cores/arduino/stm32/usb/cdc/usbd_cdc_if.c, cores/arduino/stm32/usb/cdc/usbd_cdc_if.h
Fixed error, when host send some buffer, less then minimum, and new buffer can't be allocated
I found error in my buffer flipping technology (for usb CDC). When host sends some buffer, less than maxpacket and queue is full, USBD_CDC_Receive does nothing... But, it means, that usb pcd try to fill the rest of previously allocated buffer, and it will expect, that host will send buffer, smaller that maxpacket. But as a rule it is not. So, we must clear pcd buffer in this case.
=> Fixed error, when host send some buffer, less then minimum.

cores/arduino/stm32/usb/cdc/usbd_cdc.c, cores/arduino/stm32/usb/cdc/usbd_cdc.h, cores/arduino/stm32/usb/usbd_conf.c, system/Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_ll_usb.h, system/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd.c, system/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usb.c, system/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc/usbd_cdc.h, system/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c, system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_def.h, system/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c, system/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c
Affected devices:
- STM32F103x6
- STM32F103xB
- STM32F103xG
- STM32F103xE
- STM32F102x6
- STM32F102xB
Transmission double buffering not tested yet.
Reception works. It achieve maximum CDC speed, available for this devices.
It also contains a set of fixes and improvements.
=> Receive double buffering for STM32F1xx

cores/arduino/stm32/usb/hid/usbd_hid_composite_if.c, cores/arduino/stm32/usb/hid/usbd_hid_composite_if.h, libraries/Keyboard/src/Keyboard.cpp, libraries/Mouse/src/Mouse.cpp
Avoid call twice Init/Deinit of HID composite.
/CC @roc2 this should solve your issue.
=> [USB HID] Harden init

cores/arduino/wiring_analog.c, cores/arduino/wiring_analog.h
Default is `PWM_FREQUENCY` (1000Hz).
Call `analogWriteFrequency(freq)` before `analogWrite(pin, val)`
to use the new frequency.
Note that no compute/check is performed to ensure the requested freq.
This is dependent on how the computation is currently done in analogWrite.
This limitation will be remove when Timer management will be done.
Should replace #349
=> Allow to change default PWM frequency

cores/arduino/stm32/usb/cdc/usbd_cdc_if.c
* [ #478 ] Bug USBSerial loosing characters on Linux
In CDC_connected the core reads the value of the global variable transmitStart twice. This is a problem because the variable is modified inside ISR and the value can change between the two reads. It can lead to calculating the wrong value for transmitTime which can lead to loss of data.
This proposed fix would save the value of transmitStart in a local variable, so we read the value only once.
Fixes #478
=> Fix issue #478.

variants/DISCO_L072CZ_LRWAN1/variant.cpp
Fix #479
As the board has user USB connector, enable it by default.
Anyway, SB25 and SB16 have to be closed to have USB functional.
=> [DISCO_L072CZ_LRWAN1] Enable USB clock

cores/arduino/board.h, cores/arduino/stm32/clock.c, cores/arduino/stm32/clock.h, cores/arduino/stm32/dwt.c, cores/arduino/stm32/dwt.h, cores/arduino/stm32/hw_config.c, cores/arduino/wiring_time.c, cores/arduino/wiring_time.h
- Introduce DWT for cortex supporting it (cortex-m3/m4/m7).
- Use DWT cycle counter to have `delayMicroseconds` not dependent to interrupt (example with OneWire).
- Fix rollover for `delayMicroseconds` with cortex-m0 (no DWT)
Still to provide a `delayMicroseconds` not dependent to interrupt  for cortex-m0 to allow for example OneWire usage with MCU based on this cortex.
Fix #176
=> [Time] Review delay

platform.txt
Remove `ld `option '`warn-section-align`', as by default, **SECTIONS** command
does not specify a start address for the section, let `ld `do the work.
If a start address is specified no warn was displayed.
> --warn-section-align
>     Warn if the address of an output section is changed because of
>     alignment. Typically, the alignment will be set by an input section.
>     The address will only be changed if it not explicitly specified;
>     that is, if the SECTIONS command does not specify a start address
>     for the section.
Fix #465
=> Do not warn if start of section is changed

cores/arduino/WString.cpp
Replace `strncpy()` usage in `String::remove` method by `memmove()`.
Destination and source shall not overlap when using `strncpy()` while
`memmove()` is safer alternative when overlapping.
Warning raised after moved from arm-none-eabi-gcc 6-2017-q2-update
to 8-2018-q4-major:
```
cores\arduino\WString.cpp: In member function 'void String::remove(unsigned int, unsigned int)':
cores\arduino\WString.cpp:832:10: warning: 'char* strncpy(char*, const char*, size_t)' accessing 0 or more bytes at offsets [0, 2147483647] and [0, 2147483647] may overlap up to 4294967295 bytes at offset [6442450941, 2147483647] [-Wrestrict]
strncpy(writeTo, buffer + index + count, len - index);
~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> Fix String::remove warning

cores/arduino/stm32/usb/usbd_if.c, variants/MALYANM200_F103CB/variant.cpp
**Summary**
making the renumerate function weak allows a variant to override it
**Validation**
* Ensure Travis CI build is passed.
Tested on Malyan M200 V1 rev 1, 3, and 4 (STM32F103) and on Malyan M200 V2 (STM32F070) to make sure it didn't affect others.
=> Support custom Usb reenumerate

cores/arduino/HardwareSerial.cpp, cores/arduino/HardwareSerial.h, cores/arduino/stm32/uart.c, cores/arduino/stm32/uart.h
This PR is a rework of #496  and fixes issues #494 and #467 
It hardens and enhances the original PR.
I've tested several config and it works with Arduino Serial monitor.
Note that if the same U(S)ART is used for `Serial` and `printf()` some bytes could be lost due to IRQ disabling.
@ppescher  and @benwaffle could you review and test it on your side
=> [PR 496 rework] Disable USART IRQ in uart_write and uart_debug_write 

cores/arduino/stm32/interrupt.cpp, cores/arduino/stm32/interrupt.h, cores/arduino/stm32/rtc.c, cores/arduino/stm32/rtc.h, cores/arduino/stm32/timer.c, cores/arduino/stm32/timer.h, cores/arduino/stm32/twi.c, cores/arduino/stm32/twi.h, cores/arduino/stm32/uart.c, cores/arduino/stm32/uart.h, cores/arduino/stm32/usb/usbd_conf.c, cores/arduino/stm32/usb/usbd_conf.h
Can be redefined thanks `variant.h` or `build_opt.h`
Fix #472 
| IRQ | Old | New |
| --- | --- | --- |
| Systick | 0 | 0 |
| U(S)ART | 0 | 1 |
| USB | 5 | 1 |
| I2C | 0 | 2 |
| EXTI | 6 | 3/6 |
| TIM | 14 | 3/14 |
| RTC | 2 | 2 |
_With **x/y** = x for Cortex-M0 else y_
=> Re-evaluate interrupt priority values

platform.txt
Currently when one need to debug code with full
debugging symbols (including access to macros -g3) then
the linker fails because adding -g3 causes that preprocessed
{preprocld.filepath} file contains a series of #define like:
#define __STDC__ 1
#define __STDC_VERSION__ 201112L
#define __STDC_UTF_16__ 1
#define __STDC_UTF_32__ 1
#define __STDC_HOSTED__ 1
#define __GNUC__ 7
#define __GNUC_MINOR__ 4
#define __GNUC_PATCHLEVEL__ 0
#define __VERSION__ "7.4.0"
#define __ATOMIC_RELAXED 0
#define __ATOMIC_SEQ_CST 5
#define __ATOMIC_ACQUIRE 2
#define __ATOMIC_RELEASE 3
...
which later on causes the linker to not accept such a file:
/usr/lib/gcc/arm-none-eabi/7.4.0/../../../../arm-none-eabi/bin/ld:/home/sw/Arduino/DS18B20Test/.build/preproc.ld:1: ignoring invalid character `#' in expression …
=> Add support for using -g3 compiler option

cores/arduino/avr/dtostrf.c, cores/arduino/stm32/dwt.c
This allow to build with c11 instead of gnu11 (GNU dialect of ISO C11)
Avoid `strdup `usage and use correct `asm `keyword.
Should replace #510 
Tested with `std=c99`/`11`/`17`/`18`
Also with some libraries.
=> Fix to build with ISO C standard

boards.txt, platform.txt
This PR add support of `STM32CubeProgrammer` tools:
https://www.st.com/en/development-tools/stm32cubeprog.html
Allows to unified tools used to flash STM32 based boards across supported host OS: 
* Linux
* MacOS
* Windows
Replace:
* STLink
* Serial
Add:
* DFU method using the built-in ST bootloader
It depends of https://github.com/stm32duino/Arduino_Tools/pull/34
User will have to install the `STM32CubeProgrammer` to be able to flash.
User can change the default install path but in this case, the new path have to be added in the `PATH` environment variable.
Only one definition of the tool is required in the `platform.txt`.
`{upload.protocol}` allows to select the right interface to use:
* 0: SWD
* 1: Serial (using the built-in ST bootloader)
* 2: DFU (using the built-in ST bootloader)
See …
=> Introduce STM32CubeProgrammer

cores/arduino/stm32/usb/cdc/usbd_cdc_if.c, cores/arduino/stm32/usb/hid/usbd_hid_composite_if.c, cores/arduino/stm32/usb/usbd_desc.c, cores/arduino/stm32/usb/usbd_desc.h
**Summary**
This PR clean descriptors and string formatting method in `usbd_desc.*`
This avoid duplicated functions handled by define. Only dedicated values are handled by USBD class define. This would ease further USB device class addition.
=> [USBD] Clean descriptors and string formatting method

cores/arduino/stm32/timer.c, cores/arduino/stm32/timer.h
TIM channel values used was confusing and required to map them
correctly while there is no added value to do this.
Use the HAL definition: `TIM_CHANNEL_x` will avoid any mismatch.
Fix #531
=> Fix Timer issues

boards.txt, cores/arduino/stm32/backup.h, cores/arduino/stm32/bootloader.c, cores/arduino/stm32/bootloader.h, platform.txt, variants/DIYMROE_F407VGT/ldscript.ld
Required: https://github.com/stm32duino/Arduino_Tools/pull/36
=> HID Bootloader v2.2 support

cores/arduino/stm32/twi.c, cores/arduino/stm32/twi.h, libraries/Wire/src/Wire.cpp, libraries/Wire/src/Wire.h
This PR add possibility to enable the I2C general call mode feature.
It replaces #470 .
Adding `true` to the 3 `Wire::begin()` methods will enable the general call mode else `false` per default.
/cc @benwaffle
=> [I2C]  Add general call mode settings

boards.txt, variants/DEMO_F030F4/variant.cpp, variants/DEMO_F030F4/variant.h
This PR would replace #553 from @kgamecarter.
This avoid to duplicate the variant **DEMO_F030F4** to only change HSE value.
Simply define a new board entry with the same variant and use the `-DARDUINO_{build.board}` definition
to update the HSE value and clock config.
=> [Review #553] Add STM32F030F4 Demo board 16MHz

.gitignore, cores/arduino/stm32/twi.c, cores/arduino/stm32/twi.h, libraries/Wire/src/Wire.cpp, variants/board_template/variant.h
This PR review I2C speed for series requiring I2C timing calculation
Currently:
* STM32F0
* STM32F3
* STM32F7
* STM32G0
* STM32H7
* STM32L0
* STM32L4
* STM32WB
Previously, I2C timing value for the `TIMINGR` register was hard coded for a specific I2C clock source configuration which was wrong for several target.
This PR provides dynamic calculation of this value depending of the I2C clock sources.
As this calculation of all timing values can consume huge time. By default, only the first **8** valid timing will be computed:
```
#ifndef I2C_VALID_TIMING_NBR
#define I2C_VALID_TIMING_NBR          8U
#endif
```
It can be redefined thanks the `variant.h` or `build_opt.h` or `hal_conf_extra.h` using: `I2C_VALID_TIMING_NBR`
Higher number ensure lowest clock error but require more time to compute …
=> I2C Timing

boards.txt, variants/DEMO_F030F4/variant.cpp
Currently STM32F030F4-Boards require a 8MHz or 16MHz external crystal for system clock. This variant allows for using the internal rc oscillator (HSI) to generate a 48MHz system clock without additional external components lowering BOM cost or complexity for boards without the need for high clock accuracy.
=> Add STM32F030F4 with internal rc oscillator

cores/arduino/stm32/twi.c, libraries/Wire/src/Wire.cpp
=> [I2C] Harden error management

cores/arduino/stm32/stm32_def.h
To avoid any issue with `F_CPU` value, it is defined by default to
`SystemCoreClock` value which is updated automatically after each
clock configuration update.
Some libraries use `F_CPU` at build time for conditional purpose (ex to #612).
This commit allow to redefine it at build time using `build_opt.h` or `hal_conf_extra.h`:
https://github.com/stm32duino/wiki/wiki/Custom-definitions
then it will be possible to define it as a constant.
**Important note:**
**User have to ensure to set it to the proper value.**
=> Allow F_CPU redefinition

cores/arduino/HardwareTimer.cpp, cores/arduino/HardwareTimer.h
**Summary**
Add comment on `refresh() `function usage.
By the way fixe typo in `setPrescaleFactor()`.
Fix #617
=> Add comment on refresh() function usage

cores/arduino/stm32/clock.c, cores/arduino/wiring_time.h
This PR mainly fixes issue with `delayMicroseconds()` on Cortex-M0 as for other series it uses `DWT->CYCCNT` which is more accurate.
Then OneWire is now functional on all series.
With old implementation:
With new implementation:
Fixes #412
=> [Time] delayMicroseconds() accuracy + Fix ticks per ms value used to compute micros

boards.txt, platform.txt
Library can provide a pre-compiled library.
See `precompiled` option here:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format
The .a(archive)/.so(shared object) file must be located at: `src/{build.mcu}`
So the `build.mcu` could not contain `fpu` and `float-abi` options
and should only contain `cortex-mx` value.
Else Arduino IDE, instead of searching `cortex-mx`, searches
`cortex-mx -mfpu=fpv4-sp-d16 -mfloat-abi=hard` if floating-point
options are set.
`build.flags.fp` has been added to contain floating-point options if any.
Fixes #606
=> Fix `{build.mcu}` definition

cores/arduino/HardwareTimer.cpp
**Summary**
HardwareTimer does not 0 all callbacks in the array, resulting in invoking random code
=> Fix callbacks array init. Move nptr check in the start of CCcb

libraries/SoftwareSerial/examples/SoftwareSerialExample/SoftwareSerialExample.ino, libraries/SoftwareSerial/examples/TwoPortReceive/TwoPortReceive.ino, libraries/SoftwareSerial/keywords.txt, libraries/SoftwareSerial/library.properties, libraries/SoftwareSerial/src/SoftwareSerial.cpp, libraries/SoftwareSerial/src/SoftwareSerial.h
**Summary**
This Pull Request is based on PR: Add SoftwareSerial #627 from @armint:
Add SoftwareSerial for STM32 boards.
This PR adds SoftwareSerial support for STM32 boards. The code was based on the SoftwareSerial implementation from the lpc176x arduino port and adapted for STM32. It uses the recently added HardwareTimer code for timing. The timer to be used can be defined in variant.h by defining TIMER_SERIAL. When no TIMER_SERIAL is defined it will use the simplest timer available.
Tested and working on STM32F446ZE and STM32F401RE. Works with existing SoftwareSerial example code. Tested at 9600 and 115200 baud by communicating with hardware serial interfaces and by logic analyser.
Besides PR #627, I also
* remove the actual oversampling because I already have issue with baudrate …
=> SoftwareSerial implementation

cores/arduino/pins_arduino.h, cores/arduino/stm32/analog.cpp, variants/board_template/variant.h
If no analog pin required then `NUM_ANALOG_INPUTS` and `NUM_ANALOG_FIRST` could be not defined or set to respectively `0` and `NUM_DIGITAL_PINS`.
Nevertheless, this kept ADC internal channels functional if  `HAL_ADC_MODULE_ENABLED` still defined.
=> Allow not to have analog pin

README.md, cores/arduino/stm32/twi.c, libraries/Wire/src/Wire.cpp
This solves the repeated-start issue #583 . Tested on F411RE using a MMA8451 accelerometer and OLED SSD1306 I2C peripherals. This seems to be ok but it's a little bit tricky.
It must hugely tested by the community with several I2C peripherals and several platforms.
=> Added the repeated-start feature in I2C driver

cores/arduino/stm32/usb/cdc/usbd_cdc.h, cores/arduino/stm32/usb/cdc/usbd_cdc_if.h, cores/arduino/stm32/usb/hid/usbd_hid_composite.h, cores/arduino/stm32/usb/usbd_conf.c, cores/arduino/stm32/usb/usbd_ep_conf.c, cores/arduino/stm32/usb/usbd_ep_conf.h
Endpoints (EP) configuration was not properly set
depending of USB class used and USB type (HS/FS/LS).
=> [USB] Fix endpoints configurations

cores/arduino/stm32/twi.c, libraries/Wire/src/Wire.cpp
During Non regression tests for 1.7.0 found an issue on STM32 F2 and F4 series due to #590 introduction. Using I2C EEPROM failed.
So, reverts stm32duino/Arduino_Core_STM32#590
=> Revert "Added the repeated-start feature in I2C driver"

system/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c
=> [USB] Fix EPO STALL issue in STM32 USB Device library

libraries/SrcWrapper/src/LL/stm32yyxx_ll_fmc.c, system/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_fmc.c, system/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_sdram.h, system/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_sram.h, system/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sdram.c, system/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sram.c, system/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_fmc.c
Some guards missing in the G4 and H7 HAL Cube firmware.
Instead of removing stm32yyxx_ll_fmc.c from the build add a
fix in the HAL Cube firmware.
=> Fix stm32yyxx_ll_fmc.c build issue

cores/arduino/HardwareSerial.cpp, cores/arduino/HardwareSerial.h, cores/arduino/stm32/uart.c, cores/arduino/stm32/uart.h
**Summary**
TMC2209 and 2208 drivers use UART communication with a single wire. Enabling half-duplex support in the HardwareSerial class would enable using these drivers without wasting another pin for the RX signal.
Proposed API is to enable half-duplex mode if the RX pin on the serial port is NC. Also added a method to set the half-duplex mode explicitly.
**Validation**
* Ensure Travis CI build is passed.
* Demonstrate the code is solid. [e.g. Provide a sketch]
Tested using:
https://gist.github.com/ghent360/dc2a7226919af522e4a5914da1ad5252
=> Add half-duplex support to HardwareSerial.

cores/arduino/HardwareTimer.cpp
Set TIM_OCMODE_INACTIVE when using mode TIMER_OUTPUT_COMPARE_INACTIVE
Fixes #692
=> Set TIM_OCMODE_INACTIVE when using mode TIMER_OUTPUT_COMPARE_INACTIVE

variants/DEMO_F030F4/variant.cpp, variants/DEMO_F030F4/variant.h
**Summary**
This exposes PF0 / PF1 GPIO pins, which are available on STM32F030F4 boards that do not have an external oscillator.
=> Add PF0 / PF1 pins on STM32F030F4

platform.txt
**Summary**
This PR implements the following **features**
This adds the ability to link against statically compiled library files in Arduino Libraries using the precompiled and ldflags keys described [here](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format).
Fixes #606 which I do not believe was fully fixed by https://github.com/stm32duino/Arduino_Core_STM32/pull/629
=> Add new official library.properties field for static linking flags in platform.txt compiler recipe.

cores/arduino/stm32/timer.h
If no DAC then TIM6_IRQn is already defined.
Fixes #739
=> Fix TIM6_IRQn definition

libraries/SoftwareSerial/src/SoftwareSerial.cpp
**Summary**
When SoftwareSerial was adapted from the LPC1768 version, SoftwareSerial::send was altered in a way that prevents single-pin half-duplex communication from working properly.
This change reverts to the behavior seen in other repositories using variations of this code.
This issue was discovered while testing a [Marlin pull request](https://github.com/MarlinFirmware/Marlin/pull/15655) which is adapting Marlin to work with STM32 5.7. During testing I found that one-pin communication with TMC stepper drivers did not work properly, although it did when using similar SoftwareSerial code from other sources.
The image below shows the same read command being sent to a TMC2208 stepper driver, both before and after the change in …
=> Fix single-pin half-duplex in SoftwareSerial::send

cores/arduino/HardwareTimer.cpp, cores/arduino/HardwareTimer.h
**Summary**
Added methods to check if there's an user-IRQ-handler currently attached.
This PR implements the following **feature**
**Why**
..well...first of all...why not?
The HardwareTimer, internally, knows **if** there's a callback. Exposing this to the user makes no harm.
It's a good C++ programming practice to give a way for an object to expose its status. 
Now let's talk about why should it be there.
Imagine a situation in which you want to disable the callback (for example on a channel) leaving the timer running and receiving other interrupts on other channels.
When you have multiple timers and each of them has multiple channels it's difficult to keep track of them all, moreover if they aren't enabled and disabled from the "main" schetch but by some other interrupt handler.
In a …
=> Add methods to check if there's an IRQ handler

cores/arduino/HardwareTimer.cpp, cores/arduino/HardwareTimer.h
This enables users to config timers using the HAL layers for more advanced timer
settings when needed. This is especially useful when multiple timer channels
require separate configurations under the same timer instance.
This feature is related to issue #763
=> [Timer] Add getHandle function

variants/NUCLEO_L073RZ/variant.cpp
**Summary**
This PR fixes/implements the following **bugs**
**Describe the bug**
The bug is very similar to #479 for Discovery L072CZ
I've manually applied this patch https://github.com/stm32duino/Arduino_Core_STM32/commit/59673c97667d0eb7212c46b26e5d4089615f162c to NUCLEO_L073RZ and now it works nicely as well.
**To Reproduce**
Enable "USB CDC" in Arduino_STM32 menu settings.
Connect NUCLEO_L073RZ's PA11/PA12 to a USB host.
The host reports that:
_device not accepting address 61, error -32_
This PR is just intended to apply one known good L072CZ fix onto the L073RZ target.
=> [NUCLEO_L073RZ] Enable USB clock

cores/arduino/stm32/interrupt.cpp, cores/arduino/stm32/lock_resource.h
This PR fixes GPIO EXTI usage on MP1.
=> MP1 GPIO EXTI

keywords.txt
This PR fixes a typo where the setRx and setTx methods weren't color highlighted correctly.
=> Fix keyword literal for setRx and setTx

cores/arduino/Print.cpp, cores/arduino/Print.h
This PR uses [Adafruits printf implementation](https://github.com/adafruit/ArduinoCore-samd/blob/361481d34d0e6a9d5b2cd074ee0a990d78df3396/cores/arduino/Print.cpp#L189-L197). 
For those who didn't know, printf is super useful when you want to format your output. When printf is a part of the Print class, all libraries that inherits the print class (such as Serial, LiquidCrystal, SoftwareSerial + other LCD libraries).
This PR makes this possible:
```cpp
Serial.printf("Milliseconds since start: %d\n", millis());
```
=> Add printf to print class

cores/arduino/Print.cpp, cores/arduino/Print.h, libraries/SrcWrapper/src/syscalls.c
Based on @PaulStoffregen works for Teensyduino:
https://github.com/PaulStoffregen/cores
* Remove `PRINTF_BUFFER` usage.
* Aligned declaration with `printf()` one by returning the number of characters printed (excluding the null byte used to end output to strings).
* core debug
* standard `printf` usage on the `DEBUG_UART`
* Serial over USB
Harden #780 from @MCUdude.
=> Harden Print::printf() method

cores/arduino/stm32/spi_com.c
**Summary**
The current prescaler, if the user requests a slow clock, is set to a value which makes no sense.
We should give a frequency closer to what the user asks.
**motivation** for making this change:
If a SPI device can't handle high speed clock and the user requests a slow one we should give him the slowest clock we can. The code, before the PR, had unexpected behavior which makes difficult to track down where the problem is.
**Validation**
Should work.
=> SPI: Fix prescaler at low baudrates

platform.txt
Thanks to @ilg-ul,  arm-none-eabi-gcc packages are now available from:
https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack
Release [v9.2.1-1.1](https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases/tag/v9.2.1-1.1)
Linked:
https://github.com/stm32duino/arm-none-eabi-gcc/issues/2
=> Moved from arm-none-eabi-gcc 8.2.1-1.7 to 9.2.1-1.1

cores/arduino/HardwareTimer.cpp, cores/arduino/HardwareTimer.h, cores/arduino/Tone.cpp
**Summary**
Rework HardwareTimer internal working. And add new API to pause/resume individual channel.
Main rework:
* `HAL_TIM_Base_Init()` is now called only once at object creation
* `HAL_TIM_xxx_ConfigChannel` is now done in `setMode()`
* `HAL_TIM_xxx_Start` is done in `resumeChannel()`
* use LL when possible
* Configuration are directly made through hardware register access (when possible),
then remove useless attribute
* Add new API to pause only one channel (fixes #763):
```c
pauseChannel(uint32_t channel);
resumeChannel(uint32_t channel);
```
* integration of PR #767 Flexible interrupts handling
=> HardwareTimer: rework internal mapping of arduino API to HAL/LL API

cores/arduino/HardwareTimer.cpp
**Summary**
On F1 family, input alternate function must configure GPIO in input mode
(not in alternate function like other STM32 families).
Fixes #812
=> HardwareTimer: Fix STM32F1 specific gpio configuration in case of input

libraries/SPI/src/utility/spi_com.c
This looks up the SPI module corresponding to each of pins passed and
then uses `pinmap_merge_peripheral()` to merge this in a single pin. If
not all pins map to the same SPI module, this should abort.
The `pinmap_merge_peripheral` function returns NP to indicate a mismatch
between the passed peripherals. However, when one of the arguments is
already NP, this is not propagated into the function result, instead the
other argument is simplly returned.
In this case, the merging happens in two levels: First MISO and MOSI are
merged, then SCK and SS are merged and finally the merged results are
again merged. That means that if MISO and MISO mismatch, but SCK and SS
match (or the other way around), the NP returned due to the mismatch is
ignored and the final result is not NP, so no error is …
=> Fix SPI pin matching check

cores/arduino/pins_arduino.h, cores/arduino/stm32/analog.h, cores/arduino/wiring_analog.c, libraries/SrcWrapper/src/stm32/analog.cpp, variants/BLACK_F407XX/variant.h, variants/BLUE_F407VE_Mini/variant.h, variants/board_template/variant.h
This PR improve and fixes `analogReadResolution` and `analogWriteResolution` usage following the Arduino References:
* https://www.arduino.cc/reference/en/language/functions/zero-due-mkr-family/analogreadresolution/
* https://www.arduino.cc/reference/en/language/functions/zero-due-mkr-family/analogwriteresolution/
* `DACC_RESOLUTION` is fixed to 12 bits and could not be redefined.
* `PWM_RESOLUTION` range is from 1 to 32.
* `ADC_RESOLUTION` range is from 1 to 32, internal ADC resolution used is defined to be the best match available: 6, 8, 10, 12, 14 or 16 bits (depending of the STM32 Series)
=> Fix resolution

cores/arduino/HardwareTimer.cpp
**Summary**
HardwareTimer: set callback before enabling interrupt to avoid race condition.
Takes into account race condition remark from #806
=> HardwareTimer: set callback before enabling interrupt

cores/arduino/stm32/analog.h
=> Fix build issue when TIM module is disabled or only requested

cores/arduino/HardwareTimer.cpp
**Summary**
HardwareTimer: start timer when only update interrupt needed
No more need to use setMode() when only update interrupt required.
Simplify timebase interrupt usage: see #841
=> HardwareTimer: start timer when only update interrupt needed                 

libraries/Wire/src/utility/twi.h
**Summary**
I2C: allow static redefinition of I2C buffer size.
Default buffer size is still 32, but it is now possible to redefine compilation switch: I2C_TXRX_BUFFER_SIZE
It's maximum value is 255
Now it is possible to transfer up to 255 bytes for all following cases:
* Master read
* Master write
* Slave read
* Slave write
Warning: a bug in STM32 cube HAL currently prevents, in Master mode, to send/receive exactly 255 bytes.
Issue is tracked internally, and fix should come in later release.
Nevertheless, if required, it is possible to patch the STM32 cube HAL:
for example, when working on NUCLEO_L476RG in file stm32l4xx_hal_i2c.c (adapt file name to the STM32 familly you are working on), replace all occurrences of 
`if (hi2c->XferCount < MAX_NBYTE_SIZE)`
by
`if (hi2c->XferCount <= …
=> I2C: allow static redefinition of I2C buffer size

cores/arduino/HardwareTimer.cpp
**Summary**
HardwareTimer: Clear IT flag only if callback not previously configured
rework #806 after discussion with @matthijskooijman
=> HardwareTimer: Clear IT flag only if callback not previously configured

cores/arduino/Print.cpp
Before it was only linked to U(S)ART while `Print` is a Base class.
Fixes #862
=> Print::printf() generic

libraries/Wire/src/utility/twi.c
This is related to: https://github.com/stm32duino/Arduino_Core_STM32/pull/748#pullrequestreview-343999545
When this timeout is triggered, I2C_OK was returned. This happens because in the
loop above, it checks for `(delta < I2C_TIMEOUT_TICK)`, so it breaks out of the
loop as soon as `delta == I2C_TIMEOUT_TICK`. Then, the if below checks for
`(delta > I2C_TIMEOUT_TICK)`, which is not yet false. Since the hardware reports
no errors either, I2C_OK was returned.
By using `>=` in the if rather than `>`, this is fixed and I2C_TIMEOUT is now
returned instead.
=> [I2C] Fix error reporting on I2C timeout

cores/arduino/stm32/timer.h
=> Fix TIM1_IRQn definition when TIM10 is not defined

cores/arduino/stm32/usb/cdc/usbd_cdc.c
The CDC code presents itself as a virtual serial port. However, it also
sets the "bFunctionProtocol" value to 1, which means it supports
AT-commands, which is not actually the case. This might cause problems
with some software, such as ModemManager.
Originally, ModemManager would be very liberal with probing serial
devices, using a blacklist to prevent probing non-modems such as
Arduinos.
Since version 1.7.990, it has supported a "strict" mode where it tries to be
more restrained in what devices it probes. For CDC ACM devices, this
means it will only probe devices that claim to support AT-commands.
However, it also stopped applying the blacklist (intending to eventually
remove the blacklist), meaning it would end up probing these serial ports.
This new strict policy is not the upstream …
=> [CDC]: Do not claim AT-protocol in CDC interface descriptor

libraries/Servo/src/Servo.h
**Summary**
Servo: enlarge pin number range to [0..255]
On some configurations, pin number is larger than 63:
Example: NUCLEO_F429ZI PA0 = 103
Fixes issue 
https://www.stm32duino.com/viewtopic.php?f=7&t=134
=> Servo: enlarge pin number range to [0..255]

system/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_i2c.c, system/Drivers/STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_i2c.c, system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c, system/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_i2c.c
**Summary**
Wait for end of I2C STOP before starting a new transfer. 
Fixes #864
=> I2C wait end of stop before start

boards.txt, cores/arduino/stm32/usb/usbd_desc.c, platform.txt
The main goal of this PR is to make configuration of USB details (VID, PID, manufacturer and product strings) more flexible, allowing (third-party) board.txt files more control over how a board identifies on the USB side.
A related minor change is to set the device version number to 0, since this is a value that should really be configured by the sketch (and until then, should not have a meaningful value).
See the commit messages for details.
=> USB-related improvements

cores/arduino/HardwareTimer.cpp
**Summary**
HardwareTimer: Fix ARR and CCRx computation
* protect setOverflow against underflow.
* remove -1 for MICROSEC_COMPARE_FORMAT, HERTZ_COMPARE_FORMAT and TICK_COMPARE_FORMAT.
* remove -1 in setCount() too
* Manage special case where ARR = MAX_RELOAD and 100% expected.
Fixes #897
=> HardwareTimer: Fix ARR and CCRx computation

cores/arduino/HardwareTimer.cpp, cores/arduino/HardwareTimer.h
This PR adds methods to HardwareTimer to change the "preload" setting of the overflow/ARR and CC registers. By enabling preload, updates to these registers can be made at overflow time rather than halfway a period, which can improve the output waveform, as well as prevent missing an overflow event (when decreasing the overflow value to below the current timer value).
These methods are fairly simple and use the LL_TIM HAL functions. I originally implemented this using the higher-level `TIM_Base_SetConfig` but then found that the prescaler was updated using LL_TIM functions, which did not update `_timerObj.handle.Init`, so `TIM_Base_SetConfig` would then revert to a 0 prescaler. So, following the example of `setPrescalerFactor`, these new methods just write to the registers directly with …
=> HardwareTimer: Allow setting preload enable bits

libraries/Wire/src/Wire.cpp, libraries/Wire/src/Wire.h, libraries/Wire/src/utility/twi.c, libraries/Wire/src/utility/twi.h
**Summary**
I2C buffers, as well as some other attributes of the TwoWire class,
should not be static (shared between instances),
otherwise multi instance I2C doesn't work properly.
For example when MCU is master on one instance and slave on the other,
Slave reception under interruption can happen in the middle of master transmission,
and there is conflict on the shared resources.
fixes #699
=> I2C multi instances: Remove static qualifier on TwoWire attributes

variants/Generic_F411Rx/variant.cpp
The system clock is now running at 96 MHz (and not 100 MHz) to keep compatibility with USB, which requires a 48 MHz clock. The expected external crystal/clock frequency can now be redefined at compile time. Great for those new Black Pill F411Cx boards!
=> Change clock setup for Generic F411's

libraries/SrcWrapper/src/stm32/analog.cpp
**Summary**
analogRead: don't set ADC common register when ADC doesn't support it.
STM32F103ZE: ADC3 doesn't support common settings.
__LL_ADC_COMMON_INSTANCE(ADC3) returns 0
Solve issue:
https://www.stm32duino.com/viewtopic.php?f=62&t=46&hilit=adc3&start=30
=> analogRead: don't set ADC common register when ADC doesn't support it.

variants/Generic_F410Rx/variant.cpp
Make cause pin PB10/PB11 to behave incorrectly.
=> Fix typo in Generic F410Rx pin array

libraries/SrcWrapper/src/stm32/stm32_eeprom.c
**Summary**
EEPROM hardfault: eeprom_buffer should be 8 bytes aligned
Due to some cast on (uint64_t *) of eeprom_buffer,
compiler may use asm instruction LDRD which required an alignment:
4 bytes on Armv7 architecture,
and 8 bytes (depending on SCTLR.U) on Armv6 architecture.
To fit to all cases, alignment is made on 8 bytes.
Fixes #930
=> EEPROM hardfault: eeprom_buffer should be 8 bytes aligned

libraries/SPI/src/SPI.cpp, libraries/SPI/src/SPI.h, libraries/SPI/src/utility/spi_com.c, libraries/SPI/src/utility/spi_com.h
My suggestion for #898
- optimize spi_transfer routine to use LL instead of HAL
- add SPISettings field for transmit only operations
- replace spi_send with call to spi_transfer with SPI_TRANSMITONLY flag
- allow SPI_TRANSFER_TIMEOUT redefinition
=> SPI: improvements for SPI library

variants/NUCLEO_F767ZI/variant.h, variants/REMRAM_V1/variant.h
**Summary**
EEPROM emulation: wrong flash sector used for some STM32F7 variants
Default configuration for F76xx and F77xx chip is single bank.
But HAL define FLASH_SECTOR_TOTAL doesn't represent the real number of sector,
instead, it represents the maximum number of sectors (for single and dual bank).
So for variants using F76xx and F77xx chip,
we must define FLASH_BASE_ADDRESS and FLASH_DATA_SECTOR in order to use the last sector of the flash corresponding to the default single bank configuration.
Variants concerned: NUCLEO_F767ZI and REMRAM
Fixes #297
=> EEPROM emulation: wrong flash sector used for some F7 variants

cores/arduino/HardwareTimer.cpp, cores/arduino/HardwareTimer.h, libraries/SrcWrapper/src/stm32/analog.cpp
**Summary**
* HardwareTimer: Add API to get configured mode
* analogWrite: Configure HardwareTimer mode only if not previously done  
This avoid glitch when calling analoWrite multiple time.
Also don't start again timer otherwise ther is also some glitches
Fixes #939
=> Hardwaretimer analogWrite() no glitch

.travis.yml, CI/build/platformio-builder.py, package.json, tools/platformio-build.py
This PR adds build script for @platformio and a new Travis CI environment for testing internal libraries using `platformio ci` command.
=> Add initial support for PlatformIO ecosystem

.github/actions/pio-build/Dockerfile, .github/actions/pio-build/README.md, .github/actions/pio-build/action.yml, .github/actions/pio-build/entrypoint.sh, .github/workflows/Continuous-Integration.yml, CI/build/platformio-builder.py
Create a local action for PlatformIO test and add it ti the CI workflow.
Based on @valeros Travis CI added in #924.
=> Add PlatformIO Test to the workflow

libraries/Wire/src/Wire.cpp
**Summary**
Wire: rxBuffer should be initialized before using it
rxBuffer is used within `resetRxBuffer();`
Idem for txBuffer
=> Wire: rxBuffer should be initialized before using it

cores/arduino/stm32/usb/usbd_conf.c, variants/board_template/variant.h
**Summary**
USB: Disable Vbus sensing by default
Tested on STM32F746-DISCO: 
Full Speed and High Speed
ST-link power supply and USB Power supply 
Fixes #886
=> USB: Disable Vbus sensing by default

variants/Generic_F411Cx/variant.h
Thanks @BennehBoy
https://github.com/stm32duino/Arduino_Core_STM32/issues/722#issuecomment-593125145
=> Define USER_BTN for BLACK PILL F411CE

platform.txt, system/extras/prebuild.sh
Create prebuild.sh script to perform all required actions.
Same script for all supported host OS.
Fixes #957 when path contains space.
Edit: should also fixes #359
=> Update pre-build recipe

platform.txt
Depends on https://github.com/stm32duino/Arduino_Tools/pull/56
=> Unified shell scripts naming

CI/build/arduino-cli.py, CI/build/examples/BareMinimum/BareMinimum.ino, system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rcc_ex.h, variants/Generic_F410Cx/variant.h, variants/Generic_F410Rx/variant.h
Since {whole-archive} option has been removed the CI is  not fully relevant. So need to explicitly used basic functions of the built-in library.
The arduino-cli script have been updated to handle properly  region overflowed which is not a real issue while there is no other issue.
Fix 2 issues raised using the updated BareMinimum.ino:
* [F4] Fix HAL_RCC_USART3 definition for STM32F412Cx
* [Generic F410xx] Fix wrong TIMER_SERVO definition
=> [CI] Build built-in libraries

cores/arduino/WSerial.cpp, cores/arduino/WSerial.h, cores/arduino/main.cpp
=> Fix weaked serialEventRun() not being called

platform.txt, system/ldscript.ld
This is inspired by the linker sripts on the AVR architecture, which
support a .noinit section (or any section starting with .noinit,
actually) for variables that should be allocated an address in RAM, but
not be initialized to any particular value (not even zero) on startup.
These can then be used to remember values across resets.
From the sketch perspective, this works exactly the same as on AVR: Just
annote a global variable with `__attribute__((__section__(".noinit")))`
and it will have an unpredictable value on power-up and retain its value
during resets.
To implement this without having to change all board-specific linker
scripts, the linker commandline is changed to pass the board-specific
linker script to the `--default-script` linker script, and change the
main linker script …
=> Support a .noinit section for variables

boards.txt
Looks like a copy/paste typo in the boards.txt
=> Fix typo in the Fysetc board definition

CI/build/arduino-cli.py, CI/build/conf/cores_config.json, platform.txt
It fixes the issue raised here https://github.com/arduino/arduino-cli/issues/355
Following the documentation
https://arduino.github.io/arduino-cli/platform-specification/#recipes-to-export-compiled-binary
Only one `recipe.output.tmp`_file and `recipe.output.save_file` should be defined. The ".bin" only should be copied.
Now upload with arduino-cli works as "Export compiled Binary".
=> Arduino cli fix

cores/arduino/stm32/usb/usbd_if.c, variants/Generic_F401Rx/variant.h, variants/MALYANM200_F103CB/variant.cpp, variants/MALYANM200_F103CB/variant.h, variants/MAPLEMINI_F103CB/variant.h, variants/board_template/variant.h
Previously, variants could define USB_DISC_PIN when they had an USB
attach pullup that was disabled by default and needed a pin to
be written LOW to enable it. Other hardware configurations could only
overwrite the USBD_reenumerate function, like the M200 board did.
This commit makes the pullup configuration more flexible. By defining
the appropriate macros, enabled-by-default and disabled-by-default
pullups are both supported. The output level of the pin can also be
configured. Finally, for disabled-by-default, the output mode for the
enabled state can also be configured (INPUT to leave the pin floating
and let any external transistor gate pullup enable the USB pullup, or
OUTPUT to keep the pin as OUTPUT an actively drive the transistor gate).
The new macros also take PinName constants …
=> Refactor USB pullup handling

.gitattributes, .gitignore, CI/utils/patch/CMSIS/MP1/0001-MP1-Review-HAL-default-configuration.patch, CI/utils/patch/HAL/F1/0001-F1-I2C-HAL-fix-generate-Start-only-once-Stop-is-fini.patch, CI/utils/patch/HAL/F2/0001-F2-I2C-HAL-fix-generate-Start-only-once-Stop-is-fini.patch, CI/utils/patch/HAL/F4/0001-F4-Fix-HAL_RCC_USART3-definition-for-STM32F412Cx.patch, CI/utils/patch/HAL/F4/0001-F4-I2C-HAL-fix-generate-Start-only-once-Stop-is-fini.patch, CI/utils/patch/HAL/G0/0001-G0-Fix-HAL-definition.patch, CI/utils/patch/HAL/G4/0001-G4-Fix-LL-FMC-build-issue-introduce-in-HAL-version-v.patch, CI/utils/patch/HAL/L1/0001-L1-I2C-HAL-fix-generate-Start-only-once-Stop-is-fini.patch, CI/utils/stm32common.py, CI/utils/stm32update.py, CI/utils/stm32wrapper.py
The script allows to update automatically the HAL drivers and CMSIS device from the STM32Cube
released on the [STMicroelectronics](https://github.com/STMicroelectronics) GitHub organization.
It also applied all know patch and regenerate all wrapped files.
```console
usage: stm32update.py [-h] [-c] [-s pattern]
Update HAL drivers and CMSIS devices from STM32cube released on GitHub
optional arguments:
-h, --help            show this help message and exit
-c, --check           Check versions. Default all.
-s pattern, --serie pattern
Pattern of the STM32 serie(s) to update
```
```
$ python stm32update.py -c
Updating Arduino_Core_STM32...
Updating files: 100% (456/456), done.
Updating STM32CubeF0...
Updating STM32CubeF1...
Updating STM32CubeF2...
Updating STM32CubeF3...
Updating STM32CubeF4... …
```
=> Script to update HAL drivers and CMSIS devices from the STM32Cube GitHub release

variants/Generic_F103Rx/variant.h
These lines prevented the DAC implementation from working on F103RF and F103RG.
Note that the definition is located in PeripheralPins.c.
=> Fix DAC for F103RF and RG

cores/arduino/HardwareTimer.cpp, libraries/SrcWrapper/src/stm32/pinmap.c
**Summary**
HardwareTimer: specific F1 GPIO needs Alternate Function configuration
Fixes #1036
=> HardwareTimer: specific F1 GPIO needs Alternate Function configuration

boards.txt, cores/arduino/stm32/usb/usbd_if.c, variants/BLACK_F407XX/variant.h, variants/BLUE_F407VE_Mini/variant.h, variants/Generic_F401Rx/variant.h, variants/board_template/variant.h
This fixes boards that have external and internal USB pullups, which were broken by #997, as reported in #1029.
This needs a new define in the variant for these broken boards. I added this for two boards for which I could confirm that they had an external pullup. @stas2z, you have a black-based board, could you test this PR on your board?
I found that the CoreBoard F401RC had a switchable external pullup, but also internal pullups, so I changed that one to no longer use the external pullup and just the internal pullup. @mrguen, I think you have one of these boards, could you maybe test this PR on that board?
I tested this on a custom STM32F401 board, where I added an external pullup for testing. I also tested on an unmodified Blue pill, which still works as expected.
=> Fix external and internal usb pullup

README.md
**Summary**
Add links to new STM32-base board pages.
Add links to manufacturers websites under the "More info" links.
Add device(s) column.
I took the liberty to do a bit of reformatting of the supported boards list. I've added the device(s) column so that you can search for specific devices.
There's one open question though. There was this line:
```
| :green_heart: | [Black F407VET6](https://stm32-base.org/boards/STM32F407VET6-STM32-F4VE-V2.0) | *1.4.0* | VG/ZE/ZG in *1.5.0* |
```
The ZE/ZG variant of this board must be a completely different board, as those chips have got more pins. This may need to be split into two separate rows to prevent confusion about this one.
=> Improve supported boards list

cores/arduino/HardwareTimer.cpp
**Summary**
HardwareTimer: Fix resume after pause issue introduced with G4 Cube update
New hardening has been implemented in Timer HAL (starting with G4):
The new Channel state implementation prevent to restart a channel,
if the channel has not been explicitly be stopped with HAL interface.
Arduino workaround: Channel state is forced ready when pause() or pauseChannel() is called.
=> HardwareTimer: Fix resume after pause issue introduced with G4 Cube update

libraries/Servo/src/stm32/Servo.cpp
**Summary**
HardwareTimer: fix servo regression introduced by ARR preload enabled
PR: HardwareTimer: Allow setting preload enable bits #900
introduced a regression in servo library.
=> HardwareTimer: fix servo regression introduced by ARR preload enabled

cores/arduino/HardwareTimer.cpp
**Summary**
HardwareTimer interrupt priority is currently set in the constructor inside the call to `HAL_TIM_Base_Init`. Setting the priority using `HardwareTimer::setInterruptPriority` stored the priority, but it was only applied if the timer was re-initialized. This would be unlikely to ever occur for typical HardwareTimer users.
This change applies the interrupt priority immediately in addition to storing it, so that it impacts already initialized timers.
The motivation for this change is to allow Marlin firmware to utilize the latest version of this framework, without having to maintain workarounds to ensure proper interrupt priorities.
**Validation**
I verified this fix by reworking Marlin to build with the latest code from this repo. With this fix I am able to delete Marlin's …
=> Fixed setting HardwareTimer interrupt priority

variants/PYBSTICK26_DUINO/variant.h, variants/PYBSTICK26_LITE/variant.h, variants/PYBSTICK26_PRO/variant.h, variants/PYBSTICK26_STD/variant.h
Ajout nominations port par numéro de broches Sx. Eg. S3 (broche 3) = D0 (arduino) = PB9 (port micro stm32) pour garder la cohérence avec l'utilisation de la carte sous Micropython.
Merci d'avance.
=> [PYBStick]  Add Sx pin number naming  Eg. S3 (pin 3) = D0 (arduino) = PB9 (stm32 mcu)

.github/workflows/Continuous-Integration.yml, CI/build/arduino-cli.py
With new arduino-cli v0.11.0, output management has changed.
See https://github.com/arduino/arduino-cli/pull/687
Harden the exception management to have a better output result.
=> [CI] Update after arduino-cli change

libraries/SrcWrapper/src/stm32/low_power.c
**Summary**
**Feature 1**
Currently the low power library uses HAL_PWR_EnterSTOPMode for all devices. This does not leverage the stop2 mode which is available in the STM32L4XX. This results in 4,6 uA instead of 1,35 uA in my nucleo_l412kb.
Stop1 is only required when the UART device needs to wake up. So when not used the patch calls HAL_PWREx_EnterSTOP2Mode directly.
**Feature 2**
When available use the MSI as wake up clock. This avoids starting the HSI which generates a short spike of ca 300 uA until the SystemClock_ConfigFromStop is called.
**Validation**
* Demonstrate the code is solid. [e.g. Provide a sketch]
Not adding a new sketch since no external APIs are changed by this patch. 
**Code …
=> Use more efficient mode for STM32L4XX stop mode

cores/arduino/HardwareTimer.cpp
**Summary**
HardwareTimer: getTimerClkFreq() add comment to avoid confusion
=> HardwareTimer: getTimerClkFreq() add comment to avoid confusion

CI/build/arduino-cli.py
Allow to change the default url for the board manager
=> [CI] Add url option

variants/HY_TinySTM103T/ldscript.ld
The linker script for the HY_TinySTM103T variant ignored the
LD_FLASH_OFFSET linker flags. This prevented proper operation when using
a bootloader on these boards. The linker script has been replaced with
the generic F103 linkerscript that properly implements this.
=> Fix flash offset on HY_TinySTM103T variant.

cores/arduino/stm32/timer.h, cores/arduino/stm32/uart.h
Issue reported here:
https://www.stm32duino.com/viewtopic.php?p=3722#p3722
=> [G0] Fix Timer and USART IRQ definition

cores/arduino/stm32/stm32_eeprom.h, libraries/SrcWrapper/src/stm32/stm32_eeprom.c
The EEPROM area of the stm32L0xx or stm32L1xx devices is mapped in the non volatile memory
and accessed with dedicated HAL functions.
The `eeprom_write_byte` and `eeprom_read_byte` functions are valid for this actual EEPROM area to access byte per byte. 
For stm32L0 and L1 devices the buffered method (`eeprom_buffer_fill`, `eeprom_buffer_flush`) is not well suited especially for writing.
I**t is decided to  remove `eeprom_buffer_fill`, `eeprom_buffer_flush` in case of stm32L0x and stm32L1x.**
> Note:  the eeprom_buffer structure used for buffered operations is sized by a FLASH PAGE (usually 128 or 256 bytes). For stm32L0 and stm32L1, the eeprom_buffer cannot map the whole EEPROM area, else is the time to flush (write) too long (up to 15 seconds to flush 16K).
With this patch the …
=> [WIP] stm32L0xx soc series has an embedded EEPROM

platform.txt
Fix the bug described here: https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/issues/7
=> Moved from arm-none-eabi-gcc 9.3.1-1.1 to 9.3.1-1.2

.github/actions/pio-build/entrypoint.sh, tools/platformio-build.py
This PR synchronizes the latest changes in the build script for PlatformIO.
=> Update PlatformIO scripts

system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_adc_ex.h
This PR fixes an issue where the following is returning false for the STM32F411xE chip: 
`IS_ADC_CHANNEL(ADC_CHANNEL_TEMPSENSOR) `
As a result of this the [example code on the Wiki](https://github.com/stm32duino/wiki/wiki/API#example-2) for reading the internal temperature sensor returns a result of -266 because analogRead(ATEMP) always returns 0 indicating an error.
Note: Reviewing the code it looks like the definition of ADC_CHANNEL_TEMPSENSOR is inconsistent with the definition of IS_ADC_CHANNEL for other boards too? I've only made the minimal changes for the board I own however.
=> fix IS_ADC_CHANNEL() bug on STM32F411xE variants

cores/arduino/HardwareTimer.cpp
**Summary**
HardwareTimer: pause() need to call HAL API to restore HAL state
Due to HAL Cube update (ex: for STM32L4 sha1 f41f10ebd7d73cc055449424a9dd85589de92924)
it is now required to stop timer with HAL API
otherwise HAL state is not restored to HAL_TIM_STATE_READY,
and it is not possible to `resume()` a HardwareTimer after a `pause().`
Nevertheless it is not sufficient to guarantee that timer is stopped.
specially if some channels are still running.
So it is also necessary to keep also the call to LL_TIM_DisableCounter()
=> HardwareTimer: pause() need to call HAL API to restore HAL state

variants/ARMED_V1/variant.h
**Summary**
Change the ARMED variant `TIMER_TONE` and `TIMER_SERVO` definitions to avoid timer conflicts in Marlin.
=> Change ARMED tone and servo timers

variants/Generic_F4x5RG/variant.cpp
Change 2 instances:
From:
HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_1)
To:
HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_5)
**Summary**
[x] Bug 1 - incorrect FLASH LATENCY at 168MHz causing processor crash upon startup.
Also discussed here https://community.platformio.org/t/stm32duino-stm32f405rg-on-vesc-bldc-controller/14671
=> Fix flash latency for F4x5RG running full speed at 168MHz

cores/arduino/Print.cpp, cores/arduino/Print.h, cores/arduino/Stream.h
* Moved `flush `method to `Print`.
* Added `availableForWrite `method to `Print`.
* Align `Print `API of (unsigned) long long
=> Update Print/Stream API

libraries/SrcWrapper/src/stm32/uart.c
After fixing this issue https://github.com/stm32duino/Arduino_Core_STM32/pull/1141
IRQ handler was not updated then for `USART4 `and `LPUART1 `the  `HAL_UART_IRQHandler` is not called.
Fix #1188
=> [G0] Fix USART IRQ handler

libraries/Wire/src/Wire.cpp, libraries/Wire/src/Wire.h
This PR adds a missing function declaration that aligns further with the arduino spec as specified in issue #1183 
This is to fix compilation with an external Arduino library [ArduinoECCX08](https://github.com/arduino-libraries/ArduinoECCX08)
Fixes #1183
=> Add requestFrom(uint8_t address, size_t quantity, bool sendStop)

libraries/SPI/src/SPI.cpp, libraries/SPI/src/SPI.h
#800 introduced a regression on analog pins Ax usage as CS pin.
Issue raised by @geosmall here:
https://www.stm32duino.com/viewtopic.php?f=62&p=4805#p4805
=> [SPI] Fix CS pin check

libraries/Wire/src/utility/twi.c
**Summary**
**Description**
* The slave implementation doesn't seem to work with repeated starts, but this is also a quick fix by sending out an onReceiveEvent() when getting the new address callback.
* In #488 it was mentioned to just use one write, but I think this is not good behavior, since it's not mentioned in the documentation. Nevertheless, it seems to be a quick fix, so I just created this PR.
**How it works**
* When getting the address callback, the data which has been cached is sent to an onReceiveEvent, when still in SLAVE_MODE_RECEIVE mode.
* We are resetting i2cTxRxBufferSize before calling i2c_onSlaveTransmit() in HAL_I2C_AddrCallback()
and modify the function i2c_slave_write_IT() to start writing in the i2cTxRxBuffer …
=> Wire fixes for repeated start(slave) and multiple .write in onRequestEvent()

libraries/SrcWrapper/src/stm32/uart.c
Hi,
Is there any purpose behind the NVIC UART IRQ priority being repetitively set within uart_attach_tx_callback and uart_attach_rx_callback rather than only at initialization? 
Unfortunately this prevents any runtime/external changes done to the IRQ priority since it'd constantly be reset.
If there's no problem having it this way: 
I've quickly removed the two extra setPriority calls and replaced them with a single call at init().
=> HW UART - Remove repetitive NVIC SetPriority calls

libraries/Wire/src/utility/twi.c
**Summary**
This PR allow advanced users to tweak I2C timeout.
In some real time critical devices (MakAir ventilator for example), I2C reading of any device timeout after 100ms in case of bus hardware failure (short circuit between lines or bus lines to ground).
=> allow users to tweak the I2C timeout

libraries/Wire/src/utility/twi.c
Running Marlin with USE_FULL_ASSERT defined as 1 revealed 2 asserts:
assert_param(IS_TIM_CC1_INSTANCE(htim->Instance));
while using TIM7 for TIMER_SERVO on STM32F407 - switched to TIM14
assert_param(IS_I2C_OWN_ADDRESS2(hi2c->Init.OwnAddress2));
default value was filled as 0xff from twi.c, changed to even value 0xfe.
=> Fix two assert_param calls.

CI/utils/stm32update.py
This change in the CI/utils/stm32update.py is creating a new option -a which will add a new serie in the Arduino_Core_STM32
Exemple to add the new stm32l5xx serie:
`$ python3 stm32update.py -a l5`
_Not tested_: combination of several series in '-a' option, combination of options ('-a' -'c' ...)
_TODO_: this new stm32YY serie is added at the end of the list in `STM32YYxx_CMSIS_version.md` and `STM32YYxx_HAL_Driver_version.md` files
Signed-off-by: Francois Ramu <francois.ramu@st.com>
=> script to add new serie to the Arduino_Core_STM32

cores/arduino/HardwareTimer.cpp, cores/arduino/HardwareTimer.h, cores/arduino/Tone.cpp, libraries/Servo/src/stm32/Servo.cpp
**Summary**
HardwareTimer: Fix assert failed when using TIMER_OUTPUT_COMPARE
When assert is activated there may be assert failed, specially
when using Tone or Servo with TIM6 or TIM7.
"assert_param(IS_TIM_CC1_INSTANCE(htim->Instance));"
This is due to the fact that when using timer instances without
output (like TIM6 and TIM7 specially used for Tone and Servo)
in TIMER_OUTPUT_COMPARE mode, the API setMode() requires a channel,
even if it is not used.
This was made like this to simplify the HardwareTimer driver,
and there is no functional issue, but as there is an assert failed
reported when assert is activated, this should be fixed.
TIMER_OUTPUT_COMPARE becomes obsolete, but kept for compatibility
reason.
When only timing configuration is needed, no need to set mode,
just keep the default …
=> HardwareTimer: Fix assert failed when using TIMER_OUTPUT_COMPARE

cores/arduino/avr/dtostrf.c
See https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/835
=> dtostrf should not print fractional part if prec is 0

libraries/SoftwareSerial/src/SoftwareSerial.cpp
When begining the transaction, in the SoftwareSerial::begin
, the active_listener is not yet assigned, but null.
Then it differs from _this_ but should not act as if it was listening.
This is the case when testing on nucleo_l552ze board.
Signed-off-by: Francois Ramu <francois.ramu@st.com>
=> SoftwareSerial stopListening at the begining

variants/Generic_F401Cx/variant.h, variants/Generic_F411Cx/variant.h
**Summary**
Commercially sold Blackpill F411CE boards feature a 25MHz crystal, but if a board differs, HSE_VALUE can still be overridden while keeping everything else the same. With defensive programming like this, users of a custom (or differing commercially sold) board can easily use this variant with the same chip but just a slightly different crystal.
This topic e.g. appeared in https://community.platformio.org/t/env-blackpill-f401ce-consistently-creates-bad-binaries-that-hangs-the-mcu/18567 when a user was trying to user this Arduino core with a custom board with the 3 interchangable chips F401CC, F401CE and F411CE, all having a 25MHz crystal. 
If a user would ever want to use a similiar setup but with a 25MHz crystal where the …
=> Prevent redefine of HSE_VALUE if already user-overridden

libraries/Wire/src/Wire.cpp, libraries/Wire/src/Wire.h
Wire: change definition of MASTER_ADDRESS to avoid potential conflict
Define MASTER_ADDRESS in Wire.cpp to avoid potential conflict
with other libraries.
Use 0x01 for master as it is reserved for START
and thus cannot be used by slave devices.
Fixes #1278
=> Wire: change definition of MASTER_ADDRESS to avoid potential conflict

boards.txt, variants/PRNTR_Vx/ldscript.ld
**Summary**
Update the board definition for PRNTR_V2 to support a bootloader (0x08000000 to 0x08007fff)
Updating the firmware using the build-in ROM bootloader is not very reliable via USB, the device is often not detected properly when powered in boot loader mode. Decided to add a custom boot-loader that updates the firmware from sd-card if one is present.
Update the ldscript.ld to account for the flash space used by the bootloader.
**Validation**
Tested Marlin can be build and boots correctly.
=> Add bootloader support for PRNTRBoard V2.

variants/DAISY_SEED/ldscript.ld
**Summary**
Adding this provides a memory section that can be used for DMA buffers, and other non-cacheable data so that DCache can be enabled without requiring maintenance.
=> Daisy Seed - added missing ram section to linker

libraries/SrcWrapper/src/stm32/timer.c
This PR fixes the wrong returned timer source in STM32G0xx MCUs. The G0xx controllers also have only PCLK1 (like the F0 familiy), so the function should always return 1 in this case. Otherwise, e.g. if TIM1 in combination with PWM is used, 2 is returned which will crash the function HardwareTimer::getTimerClkFreq because of an unexpected timer source.
=> fix: wrong timer source for frequency calculation with STM32G0xx controllers

cores/arduino/stm32/usb/usbd_if.c
On STM32L1xx, an internal pull-up resistor (1.5 kΩ) can be connected by software on the USB data + (DP) line.
This internal pull-up resistor is enabled if the USB is not in power-down mode and if the USB_PU bit is set.
=> [USB] Manage internal pull-up

cores/arduino/stm32/PinNamesTypes.h, libraries/SrcWrapper/src/stm32/analog.cpp
For STM32L1xx, in Cat.3, Cat.4, Cat.5 and Cat.6 devices there are up to 42 multiplexed channels organized in 2 banks.
Channels ADC_IN0 to ADC_IN31 are available in Bank A and  channels ADC_IN0b to ADC_IN31b are available in Bank B.
This PR manages the ADC channel bank thanks the `PeripheralPins.c`
Example for the Nucleo L152RE:
```patch
-  {PB_2,  ADC1, STM_PIN_DATA_EXT(STM_MODE_ANALOG, GPIO_NOPULL, 0, 0b, 0)}, // ADC_IN0b
+  {PB_2,  ADC1, STM_PIN_DATA_EXT(STM_MODE_ANALOG_ADC_CHANNEL_BANK_B, GPIO_NOPULL, 0, 0, 0)}, // ADC_IN0b
```
/cc @jeromecoutant
=> Adc channel bank support

libraries/Servo/src/Servo.h, libraries/Servo/src/stm32/Servo.cpp
**Summary**
servo: optional default servo angle on attach
Allow user to set servo default angle on attach.
Fixes #1301
=> servo: optional default servo angle on attach

cores/arduino/stm32/backup.h, cores/arduino/stm32/usb/usbd_conf.c, libraries/SrcWrapper/src/stm32/PortNames.c, libraries/SrcWrapper/src/stm32/hw_config.c
**Summary**
Enable PWR clock systematically when available
This avoid to miss it in system clock configuration,
as it is not systematically done by cubeMX
=> Enable PWR clock systematically when available

system/Drivers/CMSIS/Device/ST/STM32F1xx/Source/Templates/gcc/startup_stm32f105xc.s
**Summary**
This PR fixes the necessary initialization procedures which should be run before user code is called. 
`premain()` function in [main.cpp](/cores/arduino/main.cpp) is essential for the HAL library to initize properly, more specifically it called `HAL_Init` which setup the systick interrupt handler which is necessary for writing a hello world.....
The issue #869 has already mentioned this bug but didn't find a solution to it. After some trials and errors and comparasion between assemblies for different products, the patch here is likely solving it.
If possible, is there's any chance we talk about this a bit further because I don't know why this workaround works in fact...
**Validation**
* CI should run after the PR is posted. let's see the result 😉 …
=> Fix HAL not properly initialized on F105x series

cores/arduino/HardwareSerial.cpp, cores/arduino/HardwareSerial.h, cores/arduino/stm32/uart.h, libraries/SrcWrapper/src/stm32/uart.c
**Summary**
HardwareSerial: don't call STM32 HAL for every bytes to transfer
Instead of calling HAL for each and every bytes,
try to call it only once for a string.
Several call may be needed to manage internal circular buffer (tx_buff)
Fixes #1309
=> HardwareSerial: don't call STM32 HAL for every bytes to transfer

boards.txt, cores/arduino/stm32/stm32yyxx_hal_conf.h, libraries/SrcWrapper/src/stm32/PortNames.c, libraries/SrcWrapper/src/stm32/pinmap.c, platform.txt
* Define `USE_FULL_LL_DRIVER` at top level as more and more HAL relies on LL drivers. So enable the full LL usage to ease access.
* Clean up generic HAL conf file
* Clean up Vddio2 Independent I/Os supply setting
=> Review HAL/LL default configuration

variants/STM32H7xx/H742Z(G-I)T_H743Z(G-I)T_H747A(G-I)I_H747I(G-I)T_H750ZBT_H753ZIT_H757AII_H757IIT/variant_NUCLEO_H743ZI.cpp
**Summary**
variant NUCLEO_H743ZI: fix digitalPin typo
=> variant NUCLEO_H743ZI: fix digitalPin typo

cores/arduino/USBSerial.cpp, cores/arduino/USBSerial.h, cores/arduino/stm32/usb/cdc/usbd_cdc.c, cores/arduino/stm32/usb/cdc/usbd_cdc.h, cores/arduino/stm32/usb/cdc/usbd_cdc_if.c, cores/arduino/stm32/usb/cdc/usbd_cdc_if.h
Add api to manage the DTR usage.
Usage: 
```C++
Serial.dtr(false); // Disable the DTR
Serial.dtr(true); // Enable the DTR - default state
```
Assuming `Serial` is mapped on `SerialUSB`
Also implement `rts()` and `dtr()` to return correct state,
Fixes #1193
=> USB CDC line state

libraries/SPI/src/utility/spi_com.c, variants/STM32H7xx/H742V(G-I)(H-T)_H743V(G-I)(H-T)_H750VBT_H753VI(H-T)/generic_clock.c, variants/STM32H7xx/H742Z(G-I)T_H743Z(G-I)T_H747A(G-I)I_H747I(G-I)T_H750ZBT_H753ZIT_H757AII_H757IIT/generic_clock.c, variants/STM32H7xx/H742Z(G-I)T_H743Z(G-I)T_H747A(G-I)I_H747I(G-I)T_H750ZBT_H753ZIT_H757AII_H757IIT/variant_NUCLEO_H743ZI.cpp, variants/STM32H7xx/H743I(G-I)(K-T)_H750IBK_H753II(K-T)/generic_clock.c
- Some peripheral frequencies was not properly configured
- Fix SPI peripheral get clock frequency function
Fixes #1380 
Note that #1380 required to update third party library.
=> fix: generic H7: clock configuration

libraries/SrcWrapper/src/stm32/pinmap.c
**Summary**
Dual pad analog switch: skip gpio configuration in case of direct ADC
Fixes issue where direct ADC on Pxy_C overwrite gpio configuration of Pxy
=> Dual pad analog switch: skip gpio configuration in case of direct ADC

cores/arduino/HardwareTimer.cpp
**Summary**
HardwareTimer: update function header and parameter description
Fixes #1430
=> HardwareTimer: update function header and parameter description

cores/arduino/stm32/backup.h
Some series still require to use their name due to wrong LL API prototype using RTC parameter instead of TAMP.
=> core: backup: use register definition instead of serie name

README.md, boards.txt, variants/STM32WLxx/WL54JCI_WL55JCI_WLE4J(8-B-C)I_WLE5J(8-B-C)I/variant_NUCLEO_WL55JC1.cpp, variants/STM32WLxx/WL54JCI_WL55JCI_WLE4J(8-B-C)I_WLE5J(8-B-C)I/variant_NUCLEO_WL55JC1.h
[NUCLEO-WL55JC](https://www.st.com/en/evaluation-tools/nucleo-wl55jc.html)
=> variant: WL: add Nucleo-WL55JC1

cores/arduino/pins_arduino.h, libraries/SPI/src/SPI.cpp, libraries/SPI/src/SPI.h, libraries/Wire/src/Wire.cpp, libraries/Wire/src/Wire.h
Since `_ALTx` introduction, default Arduino API using `uint8_t` type for pin number could not use them and raised raised this error:
```log
warning: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '260' to '4' [-Woverflow]
91 | #define PB5_ALT1                (PB5  | ALT1)
|                                 ~~~~~~^~~~~~~
sketch_jul06a.ino:10:20: note: in expansion of macro 'PB5_ALT1'
10 |   SPIClass SPI_3rd(PB5_ALT1, PC11, PC10);
|                    ^~~~~~~~
```
Moving API to uint32_t allows to use `_ALTx`, anyway some libraries used the default pin definition as an uint8_t from the variant definition, for example: 
```C
#ifndef PIN_SPI_MOSI
#define PIN_SPI_MOSI          PB5_ALT1
#endif
```
Which is stored in:
```C
static const uint32_t MISO = …
```
=> library: Wire/SPI: change default pins type

platform.txt, system/extras/prebuild.sh
See:
https://github.com/arduino/arduino-cli/issues/1338
When the above issue will be fix. This change should be reviewed.
This is backward compatible.
=> platform: use build.opt instead of build_opt.h

libraries/EEPROM/src/utility/stm32_eeprom.c
`FLASH_SIZE` defined by the CMSIS Device Peripheral Access Layer Header File is the maximum one of a product line.
So depending of the mcu this is not the correct one.
As an example, L432KC have 256 KB while L432Kb has 128 KB.
Using `LL_GetFlashSize()` allows to get the correct FLASH size.
Fixes #1316
=> fix: library: EEPROM: use correct flash size

boards.txt, platform.txt
This PR add a new menu `Debug information`.
By default it is not enabled. Enable it will produce debugging information.
It also fix the `Optimize` menu which displayed `Debug (-g)` instead of "Debug (-Og)".
Fixes #873
For further reading: https://gcc.gnu.org/onlinedocs/gcc/Debugging-Options.html#Debugging-Options
/CC @matthijskooijman
=> config: add debug information menu

tools/platformio/platformio-build.py
**Summary**
This PR fixes **bug**
Arduino Core STM32 provides a platformio-build.py file that sets compiler build flags for Arduino Core STM32 in platformio. This file sets the -mfpu flag automatically for every cortex-m4 MCU. But according to the CMSIS drivers, the STM32WL55 does not contain an FPU, causing this python script to set the wrong compile time flags. The proposed PR fixes this by excluding the -mfpu option from the CPPDEFINES flags. 
**Validation**
The following sketch won't compile without it, but will with this fix:
```
#include <Arduino.h>
void setup() {
}
void loop() {
}
```
Fixes #1473
=> exclude fpu options from stm32wl55

cores/arduino/wiring_constants.h
Current version does not wrap arguments in "()", so works incorrectly when used like this:
```
bitWrite(var, bit, cond?1:0);
```
Same as in here: https://github.com/espressif/arduino-esp32/issues/4466
=> Fix `bitWrite` with parenthesis

libraries/SPI/src/utility/spi_com.c, libraries/Wire/src/utility/twi.c
Some series provides the `HAL_RCCEx_GetPeriphCLKFreq()` which returns the peripheral clock frequency based on Peripheral clock identifier.
=> library: enhance peripheral clock frequency management

libraries/SPI/src/utility/spi_com.c
- ensure peripheral reset
- set MasterKeepIOState to avoid glitches 
This could help on #1294
=> library: spi: enhancement

variants/STM32L4xx/L4R5Z(G-I)Y_L4R9Z(G-I)Y_L4S5ZIY_L4S9ZIY/variant_SWAN_R5.h
**Summary**
update SPI pins (MOSI, MISO, SCK, SS) for Swan_R5
[Bug] SPI does not trigger the appropriate pins.
I work at Blues Wireless. During preparation and testing of the Swan, I discovered the SPI pins were not functional through the Feather pinouts.
**Validation**
* I have used the code to drive an MCP23S17 from the Swan.
It's all in the preprocessor, and it was copied from the existing pattern.
=> chore: update SPI pins for Swan_R5

libraries/SrcWrapper/src/stm32/analog.cpp
bsp: analog: use register definition instead of serie name
bsp: analog: handle `ADC_VER_V5_V90 `available with some ST32H7xx
=> bsp: ADC enhancements

libraries/SPI/src/utility/spi_com.c, libraries/SPI/src/utility/spi_com.h
**Summary**
spi: Add delay before disabling SPI to avoid truncated clock/data signals
Add a delay before disabling SPI otherwise last-bit/last-clock
may be truncated.
See https://github.com/stm32duino/Arduino_Core_STM32/issues/1294
Computed delay is half SPI clock.
Fixes #1294
=> spi: Add delay before disabling SPI to avoid truncated clock/data signals

libraries/SrcWrapper/src/stm32/uart.c
Required to be able to wake up from LPUART1 in deep sleep mode.
=>  fix(usart): enable peripheral bus clock when SRD domain is in DRUN

README.md, boards.txt
This PR is a workaround to allow flashing the Swan board at once. An issue is under investigations by ST BL team.
While waiting to have their return adding `-ob nBOOT0=0 -ob nBOOT0=1` to the upload options allows to properly flash and run the application.
Fixes #1495
During the test I found an issue with the STM32cubeProgrammer script due to the use of '=' in option.
I've push a fix in the [stm32duino/Arduino_Tools](https://github.com/stm32duino/Arduino_Tools) repo: https://github.com/stm32duino/Arduino_Tools/commit/1bce38f76f453adcc90ee4c21b51d498b22c3756
It will be available with the 2.1.0 version.
/CC @zfields @bsatrom
=> Move Swan board to dedicated menu and add a workaround for SWD upload method

system/STM32F2xx/stm32f2xx_hal_conf_default.h
Nucleo F207ZG has a LAN8742A.
Fix https://github.com/stm32duino/STM32Ethernet/issues/56
=> fix(F2): Ethernet peripheral configuration for LAN8742A

cores/arduino/HardwareTimer.cpp, cores/arduino/HardwareTimer.h
Previously, the only way to initialize a HardwareTimer instance was to
pass an instance to the constructor. When using a global (more
specifically, with static storage duration) HardwareTimer instance, the
initialization would happen early in startup, before main() and setup()
had a chance to run. This would mean that on any errors (e.g. no timer
found for a specific pin when using e.g. pinmap_peripheral), the board
would just lock up in early startup, unable to show a meaningful error
at all.
To prevent this, you would have to allocate the HardwareTimer object
dynamically on the heap, but that is not always a good idea from a
memory management perspective.
This commit adds an argumentless constructor that does not initialize
the timer yet, and a setup() method that accepts the timer …
=> HardwareTimer: Allow delaying initialization to setup method

cores/arduino/HardwareTimer.cpp, cores/arduino/HardwareTimer.h
**Summary**
HardwareTimer: Add API to check whether timer/channels are running
* bool isRunning(); //returns true if HardwareTimer is running
* bool isRunningChannel(channel); //returns true if channel is running
Fixes #1525
=> HardwareTimer: Add API to check whether timer/channels are running

variants/STM32F0xx/F070CBT/MALYANMx00_F070CB.ld, variants/STM32F0xx/F070CBT/startup_Mx00_f070xb.S, variants/STM32F1xx/F103C4T_F103C6(T-U)/variant_BLUEPILL_F103C6.h, variants/STM32F1xx/F103C8T_F103CB(T-U)/startup_M200_f103xb.S, variants/STM32F1xx/F103C8T_F103CB(T-U)/variant_AFROFLIGHT_F103CB_XX.h, variants/STM32F1xx/F103C8T_F103CB(T-U)/variant_MALYANM200_F103CB.h, variants/STM32F1xx/F103C8T_F103CB(T-U)/variant_PILL_F103Cx.h, variants/STM32F3xx/F303R(B-C)T/variant_OLIMEXINO_STM32F3.h, variants/STM32F4xx/F413Z(G-H)(J-T)_F423ZH(J-T)/variant_DISCO_F413ZH.cpp, variants/STM32H7xx/H742V(G-I)(H-T)_H743V(G-I)(H-T)_H750VBT_H753VI(H-T)/ldscript.ld, variants/STM32L0xx/L072R(B-Z)T_L073R(B-Z)T_L083R(B-Z)T/variant_PX_HER0.h, variants/STM32MP1xx/MP153AAC_MP153CAC_MP153DAC_MP153FAC_MP157AAC_MP157CAC_MP157DAC_MP157FAC/ldscript.ld, variants/STM32MP1xx/MP153AAC_MP153CAC_MP153DAC_MP153FAC_MP157AAC_MP157CAC_MP157DAC_MP157FAC/variant_STM32MP157_DK.cpp, variants/STM32WBxx/WB55C(C-E-G)U/ldscript.ld, variants/STM32WBxx/WB55R(C-E-G)V/ldscript.ld, variants/STM32WBxx/WB5MMGH/ldscript.ld
Found via `codespell -q 3 -L aes,busses,cas,dout,exten,hsi,nd,pres,serie,sinc,te,ue`
Related to #1551
=> Fix typos in variants/ subdirectory 

cores/arduino/HardwareTimer.cpp
**Summary**
HardwareTimer: start timer in case only CC interrupts are used
Start timer in case only CaptureCompare interrupts are used,
without update interrupt (and without pin used).
fixes #1544
=> HardwareTimer: start timer in case only CC interrupts are used

cores/arduino/HardwareTimer.cpp
**Summary**
HardwareTimer:
* fix typo in comments
* fix obvious ICPolarity wrong setting
=> HardwareTimer: fix typo in comments and obvious  ICPolarity wrong setting

cores/arduino/HardwareTimer.cpp
**Summary**
HardwareTimer: remove useless variable timAssociatedInputChannel
Compilation warning introduced by #1550
Fixes #1557
=> HardwareTimer: remove useless variable timAssociatedInputChannel

variants/STM32H7xx/H742V(G-I)(H-T)_H743V(G-I)(H-T)_H750VBT_H753VI(H-T)/variant_DevEBoxH7xx.cpp, variants/STM32H7xx/H742V(G-I)(H-T)_H743V(G-I)(H-T)_H750VBT_H753VI(H-T)/variant_WeActMiniH7xx.cpp
* fix variant WeActMiniH7xx: ena peripheral pll clks 
in previous commit  https://github.com/stm32duino/Arduino_Core_STM32/pull/1552 some clocks from PLL2, PLL3
are not distributed to some peripherals
originally to save some power. However, users using those
pheriperials may mistake that it is not working
this fix distributes the missed out PLL clocks to all pheripherals
those clocks are at 80 Mhz
* made the same fixes for DevEBoxH7xx
Please, Make sure that your PR is not a duplicate.
Search among the [Pull request](https://github.com/stm32duino/Arduino_Core_STM32/pulls) before creating one.
IMPORTANT: Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.
Thanks for submitting a pull request.
Please provide enough information so that others can …
=> fix variant WeActMiniH7xx, DevEBoxH7xx: ena peripheral pll clks

libraries/SrcWrapper/src/stm32/interrupt.cpp
**Summary**
interrupts: Disable EXTI when disabling interrupt
When disabling interrupt, it should be done at both NVIC and EXTI level.
This avoid to have pending interrupt at EXTI level after call to
stm32_interrupt_disable(), which could fire the callback as soon as
new call to attachInterrupt(), even without new gpio change.
This PR aims to replace/simplify #1258 (which also replace #1168)
=> interrupts: Disable EXTI when disabling interrupt

cores/arduino/WInterrupts.h, cores/arduino/wiring.h
**Summary**
Interrupts: remove C prototype and keep only C++ prototypes
attachInterrupt() C prototypes was not usable from C source file
(inheritance of former pure C implementation), and causes ambiguity
when used with lambda function as callback
Fixes #1601
=> Interrupts: remove C prototype and keep only C++ prototypes

CI/update/stm32cube.py
**Summary**
ci(stm32cube): manage Release candidate for HAL/CMSIS versions
=> ci(stm32cube): manage Release candidate for HAL/CMSIS versions

cores/arduino/HardwareSerial.cpp, cores/arduino/HardwareSerial.h, cores/arduino/stm32/uart.h, libraries/SrcWrapper/src/stm32/uart.c
Add hardware flow control configuration APIs for U(S)ART. (list item of #1418)
```C++
void setRts(_rts);
void setCts(_cts);
void setRtsCts(_rts, _cts);
```
You can enable flow control on RTS/CTS separately, or enable both.
These APIs accept either uint32_t pin number or PinName.
* All CI checks are passed.
* I tested RTS/CTS controls with logic analyzer.
* Tested on STM32L476RG. (Our product development board)
=> [U(S)ART] hardware flow control support

system/Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_rcc.c
**Summary**
system(U5): HAL RCC should restore PWR clock after clock configuration
Internal ticket 112307
=> system(U5): HAL RCC should restore PWR clock after clock configuration

cores/arduino/stm32/usb/usbd_conf.c, cores/arduino/stm32/usb/usbd_conf.h, variants/STM32L5xx/L552Z(C-E)TxQ_L562ZETxQ/variant_NUCLEO_L552ZE_Q.h, variants/STM32U5xx/U575A(G-I)IxQ_U585AIIxQ/variant_B_U585I_IOT02A.h, variants/STM32U5xx/U575Z(G-I)TxQ_U585ZETxQ/variant_NUCLEO_U575ZI_Q.h
**Summary**
cores(U5): support USB Type-C on U5
Only USB legacy on Type-C, no UCPD.
Hardening of TCPP default legacy state,
which applies to U5 as well as L5 series.
Tested:
* AnalogReadSerial with "USB support CDC (generic Serial supersede USART)
* Both Nucleo-U575zi-Q and B-U585I-IOT02A boards
* Both TypeC <--> TypeC  and  TypeC <-->TypeA  cables
Note: #1639 is needed
=> cores(U5): support USB Type-C on U5

CI/build/arduino-cli.py
If error comes from the full line of code column number is not available.
Ex:
```
system/STM32H7xx/system_stm32h7xx.c:68: error: unterminated #if
68 | #if defined(DUAL_CORE) && defined(CORE_CM4)
|
```
=> fix(cli): optional column number in error pattern

system/STM32F0xx/system_stm32f0xx.c, system/STM32F1xx/system_stm32f1xx.c, system/STM32F2xx/system_stm32f2xx.c, system/STM32F3xx/system_stm32f3xx.c, system/STM32F4xx/system_stm32f4xx.c, system/STM32F7xx/system_stm32f7xx.c, system/STM32G0xx/system_stm32g0xx.c, system/STM32G4xx/system_stm32g4xx.c, system/STM32H7xx/system_stm32h7xx.c, system/STM32L0xx/system_stm32l0xx.c, system/STM32L1xx/system_stm32l1xx.c, system/STM32L4xx/system_stm32l4xx.c, system/STM32L5xx/system_stm32l5xx_ns.c, system/STM32U5xx/system_stm32u5xx.c, system/STM32WBxx/system_stm32wbxx.c, system/STM32WLxx/system_stm32wlxx.c
**Summary**
After UART Bootloader to jump to application, 2 issues prevent application to run properly:
* Bootloader changes VTOR register and did not restore it when jumping to application
It is necessary that application set VTOR unconditionally
* Bootloader set PLL as SystemClock and keep it when jumping to application
This prevent any further configuration of the PLL.
It is necessary change SystemClock source, for example revert to default SystemClock (HSI or MSI) before any further PLL configuration.
Fixes #1637
=> Bootloader jump to application

libraries/Wire/src/Wire.cpp, libraries/Wire/src/Wire.h
**Summary**
Wire: implement STOP sequence to recover I2C bus.
Useful in case of bus stuck after a reset for example
Fixes #1661
=> Wire: implement STOP sequence to recover I2C bus.

boards.txt
**Summary**
feat: Add No Optimization (-O0) option to menus
=> feat: Add No Optimization (-O0) option to menus

cores/arduino/HardwareSerial.h, libraries/SPI/src/SPI.h, libraries/Wire/src/Wire.h
**Summary**
feat: Add STM32Cube HAL getter to SPI, Wire and HardwareSerial
Could be used for example to mix Arduino API and STM32Cube HAL API.
For example to configure DMA.
Warning: Use at your own risk
Fixes #1035
=> feat: Add STM32Cube HAL getter to SPI, Wire and HardwareSerial

system/Drivers/CMSIS/Device/ST/STM32WBxx/Include/stm32wb10xx.h, system/Drivers/CMSIS/Device/ST/STM32WBxx/Include/stm32wb15xx.h, system/Drivers/CMSIS/Device/ST/STM32WBxx/Include/stm32wbxx.h, system/Drivers/CMSIS/Device/ST/STM32WBxx/README.md, system/Drivers/CMSIS/Device/ST/STM32WBxx/Release_Notes.html, system/Drivers/CMSIS/Device/ST/STM32YYxx_CMSIS_version.md, system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_adc.h, system/Drivers/STM32WBxx_HAL_Driver/README.md, system/Drivers/STM32WBxx_HAL_Driver/Release_Notes.html, system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal.c, system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_adc.c, system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_adc.c, system/Drivers/STM32YYxx_HAL_Driver_version.md
system(WB) update STM32WBxx HAL Drivers to v1.10.1
system(WB): update STM32WBxx CMSIS Drivers to v1.10.1
=> system(WB) update STM32WBxx HAL Drivers to v1.10.1 and CMSIS Drivers to v1.10.1

boards.txt
Previous value for `BluesW.menu.upload_method.swdMethod.upload.options` causes option bytes to become corrupted.
Fix leverages `ERASE` option provided by `stm32CubeProg.sh`, which includes `-e all` in the parameters provided to `STM32_Programmer_CLI`.
=> fix: Stabilize SWD Programming for Swan (STM32L4R5)

cores/arduino/HardwareSerial.h
core: fix HardwareSerial compilation failed when USART disabled
Fixes #1695
=> core: fix HardwareSerial compilation failed when USART disabled

libraries/Wire/src/Wire.cpp, libraries/Wire/src/Wire.h, libraries/Wire/src/utility/twi.c, libraries/Wire/src/utility/twi.h
On a few devboards running linux, dragonboard410c, pi4 etc, I am
seeing issues with i2cdetect and other i2c bash utilities where
the stm32 holds the SCL line low and hangs the bus. This seems
to fix the issue.
Signed-off-by: Sahaj Sarup <sahaj.sarup@linaro.org>
=> wire: add fix for toggling NoStretch

tools/platformio/platformio-build.py
I tried to build FreeRTOS for STM32L552ZE-Q with using PlatformIO bud failed.
https://github.com/stm32duino/STM32FreeRTOS/issues/51
However, it succeeds on Arduino IDE.
I see log of them and I found that PlatformIO does not add the following flags for arm-none-eabi-gcc and arm-none-eabi-g++.
```
-mfpu=fpv4-sp-d16
-mfloat-abi=hard
```
The modification of this PR allow building FreeRTOS for STM32L552ZE-Q on PlatformIO.
Thank you.
=> Add flags about fpv4 for cortex-m33 on platformio-build.py

libraries/SrcWrapper/src/stm32/clock.c
It is kind of revert commit 15dc04b0a0ceaa612e80f7c26d78c4fb68aa8b56.
Note:  `delayMicroseconds()` does not rely anymore on `micros()` so accuracy is less important.
Fixes #1680
/cc @matthijskooijman
=> fix: make micros compatible with ISR

cores/arduino/stm32/stm32yyxx_hal_conf.h, libraries/SrcWrapper/src/stm32/clock.c, libraries/SrcWrapper/src/stm32/hw_config.c
Thanks to @patricklaf comment.
https://github.com/stm32duino/Arduino_Core_STM32/commit/f44e2aaf871e3048bf6684973b2ae45f783b79b2#r73522167
=> fix: allow to disable HAL CRC module

cores/arduino/HardwareTimer.h, libraries/SrcWrapper/src/HardwareTimer.cpp
**Summary**
HardwareTimer: call refresh() after parameter update when timer not running
In case timer is not running,
after an update of parameters (setOverflow(), setCaptureCompare(), setPrescaleFactor()),
call refresh() to force register update independently of Preload setting.
Fixes https://www.stm32duino.com/viewtopic.php?f=7&t=1563
=> HardwareTimer: call refresh() after parameter update when timer not running

boards.txt, platform.txt
Arduino-cli allows to override some standard Arduino build property with a custom value.
Previously some of them was already used in `boards.txt`/`platform.txt` preventing to use it.
This PR remove this usage by defining some custom properties making the default one empty and usable by end user.
`build.extra_flags`, `compiler.c.extra_flags` and `compiler.S.extra_flags` can now be redefined all other were already empty by default.
Fixes #1709
=> feat: allows arduino-cli to override build property

cores/arduino/stm32/analog.h, cores/arduino/stm32/timer.h, libraries/SrcWrapper/src/HardwareTimer.cpp, libraries/SrcWrapper/src/stm32/analog.cpp, libraries/SrcWrapper/src/stm32/timer.c
This PR exports some getter api:
```
uint32_t get_adc_channel(PinName pin, uint32_t *bank);
uint32_t get_adc_internal_channel(PinName pin);
uint32_t get_dac_channel(PinName pin);
```
Fixes #1669
=> Review get adc/dac/timer channel functions

boards.txt, cores/arduino/core_debug.h, cores/arduino/stm32/stm32_def.h, libraries/SrcWrapper/src/stm32/stm32_def.c, platform.txt, system/extras/prebuild.sh, variants/STM32MP1xx/MP153AAC_MP153CAC_MP153DAC_MP153FAC_MP157AAC_MP157CAC_MP157DAC_MP157FAC/README.md
This PR refactor the core debug log management:
- Add menu entries to enable the Core logs:
- Remove `CORE_DEBUG` usage as replaced by the menu.
- Refactor error handler definition to save space when core logs are not enabled (removed unused const char array from .rodata).
When core logs are not enable, `NDEBUG` is defined and used to prevent  print from `Error_Handler` thanks to `core_debug.`
* Before this PR:
> Sketch uses 18780 bytes (7%) of program storage space. Maximum is 262144 bytes.
> Global variables use 896 bytes (1%) of dynamic memory, leaving 64640 bytes for local variables. Maximum is 65536 bytes.
* With this PR and Core logs disabled:
> Sketch uses 17832 bytes (6%) of program storage space. Maximum is 262144 bytes.
> Global variables use 896 bytes (1%) of dynamic memory, …
=> Error management: save space when core logs are not enabled

CI/build/platformio-builder.py
By default `Keyboard` and `Mouse` libraries are skipped as they may require additional configuration steps
Related #1743
=> Add functionality to ignore library examples in CI for PlatformIO

README.md, boards.txt, variants/STM32G0xx/G070RBT/variant_NUCLEO_G070RB.cpp, variants/STM32G0xx/G070RBT/variant_NUCLEO_G070RB.h
[Nucleo_g070rb
](https://www.st.com/en/evaluation-tools/nucleo-g070rb.html)
- GPIO
- U(S)ART
- ADC
- DAC
- I2C
- SPI
- Timer
- RTC
- Low Power
- EEPROM
Fixes #1147 and fixes #1651
=> variant: G0: add Nucleo-G070RB

boards.txt, platform.txt
```
Linting platform in STMicroelectronics\hardware\stm32\2.3.0
ERROR: Missing upload.tool.<protocol_name> property for board ID(s) Nucleo_144, Nucleo_64, Nucleo_32, Disco, Eval,
STM32MP1, GenF0, GenF1, GenF2, GenF3, GenF4, GenF7, GenG0, GenG4, GenH7, GenL0, GenL1, GenL4, GenL5, GenU5,
GenWB, GenWL, 3dprinter, BluesW, Elecgator, ESC_board, Garatronic, GenFlight, LoRa, Midatronics
See: https://arduino.github.io/arduino-cli/latest/platform-specification/#sketch-upload-configuration
(Rule PF016)
WARNING: Missing upload.maximum_size property for board ID(s) Nucleo_144, Nucleo_64, Nucleo_32, Disco, Eval, STM32MP1,
GenF0, GenF1, GenF2, GenF3, GenF4, GenF7, GenG0, GenG4, GenH7, GenL0, GenL1, GenL4, GenL5, GenU5, GenWB, GenWL,
3dprinter, BluesW, Elecgator, ESC_board, Garatronic, GenFlight, LoRa, …
```
=> ci(arduino-lint): fix new error raised by new version 1.2.1

cores/arduino/Print.cpp, cores/arduino/Print.h, cores/arduino/core_debug.c, cores/arduino/core_debug.h
**Summary**
This PR makes some changes to the printing/printf code, both in the Print class and in `core_debug`.
The main change that I needed is to add a "v" version of the `core_debug()` function. Like `vprintf` vs `printf`, the `vcore_debug` function does not accept individual arguments to interpolate into format string, but a `va_list` instance. This allows it to be called from another function that is itself a varargs function and forwards its variable arguments.
I originally thought I needed this for `Print::printf`, so I implemented `Print::vprintf` too. I ended up using `core_debug()` instead, but the `vprintf()` implementation might be useful for others (and adds zero code space if unused), so I just added it.
Finally, when looking at the `core_debug()` code, I noticed the …
=> Print and debug improvements

system/extras/prebuild.sh
and avoid to append same line at each build.
/cc @TDhaouST
=> fix(build_opt): add double quotes to allow space in path

libraries/SrcWrapper/src/stm32/analog.cpp
**Motivation**
When using the STM32Examples (internal channels) sketch to read the internal ADC values from the NUCLEO-WL55JC (STM32WLxx) the following is observed:
VRef(mv)= 3223  Temp(°C)= -92   Vbat(mv)= 598   A0(mv)= 0
VRef(mv)= 3274  Temp(°C)= -88   Vbat(mv)= 606   A0(mv)= 0
VRef(mv)= 3223  Temp(°C)= -91   Vbat(mv)= 597   A0(mv)= 0
Note that VRef is a little on the low side for USB power and that Temp provides an implausible and erroneous negative number. Vbat is also somewhat questionable.
With the small fix applied the following is observed:
VRef(mv)= 3308  Temp(°C)= 28    Vbat(mv)= 1109  A0(mv)= 0
VRef(mv)= 3310  Temp(°C)= 28    Vbat(mv)= 1110  A0(mv)= 0
VRef(mv)= 3313  Temp(°C)= 29    Vbat(mv)= 1110  A0(mv)= 0
Note that …
=> Fix for ADC timing for NUCLEO-WL55JC (STM32WLxx)

.github/workflows/arduino-lint.yml, boards.txt, platform.txt
Currently, defining a default upload tools prevents flashing with arduino-cli as default methods is always used even if new one is passed as fqbn parameters.
See:
#1654
https://github.com/arduino/arduino-cli/issues/1444
So force usage of 1.2.0 release of the arduino-lint.
=> arduino-lint 1.2.1 requirements fix prevents upload with arduino-cli

libraries/SoftwareSerial/src/SoftwareSerial.cpp
**Summary**
When working with single-pin half-duplex SoftwareSerial, I noticed that after the call to `listen()` receiving data is not possible until data is written. In fact `setRXTX(true)` is only called within `send()`, which in turn is only called as long as `active_out` is set (i.e. ongoing transmission). Since at the beginning of `listen()` completion of any ongoing transmissions is awaited, the SoftwareSerial will not actively listen before another transmission is completed.
This occurs if the communication is not initiated by the STM32. Otherwise, one would simply call `listen()` and then send whatever will trigger the other side to respond. 
In my case, I wanted to use a second line to indicate the direction of …
=> fix(SoftwareSerial):  correct TX to RX switch when using half-duplex

libraries/Wire/src/utility/twi.c
Previously, i2c_master_write and i2c_master_read returned I2C_OK if first HAL call returned HAL_BUSY which was not correct.
Now make sure the i2c is ready, which guarantees a good initialization of the read or write sequence.
**Validation**
Fixes #1774
=> fix(wire): ensure i2c bus is ready

variants/STM32F0xx/F031K6T/variant_NUCLEO_F031K6.cpp
fix: variant Nucleo F031K6: switch PLL source to HSI
On Nucleo F031K6, the HSE bypass through MCO from STLink
is not configured by default
(It would need SolderBridge configuration)
Thus use HSI by default.
=> fix: variant Nucleo F031K6: switch PLL source to HSI

README.md
fix: readme: typo Generic STM32F207ZG and STM32F217ZG
Fix #1779
=> fix: readme: typo Generic STM32F207ZG and STM32F217ZG

cores/arduino/stm32/uart.h, libraries/SrcWrapper/src/stm32/uart.c
**Summary**
fix: take into account STM32G0B0 USART IRQ multiplexing specificities
Fixes CI  failed compilation of PR #1784
=> fix: take into account STM32G0B0 USART IRQ multiplexing specificities

variants/STM32G4xx/G473R(B-C-E)T_G474R(B-C-E)T_G483RET_G484RET/variant_NUCLEO_G474RE.h
fix: Nucleo G474RE: define LED_BUILTIN in the proper way
=> fix: Nucleo G474RE: define LED_BUILTIN in the proper way

libraries/Wire/src/Wire.cpp
**Summary**
fix(Wire): in case of slave, (re)enable interrupt when configuring clock
Because TwoWire::setClock() calls i2c_setTiming()
which disable/(re)enable I2C Hardware,
it is necessary to restore interrupts.
Fixes #1804
=> fix(Wire): in case of slave, (re)enable interrupt when configuring clock

libraries/Wire/src/utility/twi.c
I2C slave: Enable multi slave address onReceive/onRequest handling.
Currently the I2C slave onRequest/onReceive events are only triggered if matching OwnAddress1.
With this proposed change the events are triggered for any configured, enabled and matching slave address.
=> I2C slave: Enable multi slave address handling

cores/arduino/stm32/stm32_def.h, libraries/SrcWrapper/src/stm32/pinmap.c
=> fix: set only AF mode for mcu with single AF

boards.txt
There was a typo in boards.txt, in the definition of the THUNDERPACK_L072, where an extra "." was left in a line. This commit fixes that.
```
GenL0.menu.pnum.THUNDERPACK_L072..build.peripheral_pins=-DCUSTOM_PERIPHERAL_PINS
```
=> fix: typo "..build.peripheral_pins"

cores/arduino/stm32/uart.h, libraries/SrcWrapper/src/stm32/uart.c, libraries/SrcWrapper/src/syscalls.c
Fixes #1789 
Clean up the debug uart functions
Core debug is now half duplex by default if not linked to another Serial instance.
Tested:
- Serial and debug on the same U(S)ART
- Serial and debug on different U(S)ART
=> Core debug hardening

boards.txt, variants/STM32U5xx/U575Z(G-I)TxQ_U585ZITxQ/boards_entry.txt, variants/STM32U5xx/U575Z(G-I)TxQ_U585ZITxQ/ldscript.ld
The xml describing those mcu give 256Kb ram.
Issue raised internally to fix this then it will be corrected in generated files.
Based on RM0456:
SRAM 1/2/3 are consecutive but SRAM4 not.
Fixes #1827
=> fix: U575Z(G-I)TxQ_U585ZITxQ ram issue

variants/STM32L4xx/L4R5Z(G-I)Y_L4R9Z(G-I)Y_L4S5ZIY_L4S9ZIY/variant_SWAN_R5.h
Please, Make sure that your PR is not a duplicate.
Search among the [Pull request](https://github.com/stm32duino/Arduino_Core_STM32/pulls) before creating one.
IMPORTANT: Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.
Thanks for submitting a pull request.
Please provide enough information so that others can review your pull request:
**Summary**
Explain the **motivation** for making this change. What existing problem does the pull request solve?
**Validation**
* Demonstrate the code is solid. [e.g. Provide a sketch]
* Ensure AStyle check is passed thanks CI
Fixes #xxx
=> feat: Name Swan Virtual COM Port pins

variants/STM32L4xx/L4R5Z(G-I)Y_L4R9Z(G-I)Y_L4S5ZIY_L4S9ZIY/variant_SWAN_R5.h
Clarify Swan LP1 interface defines.
_We liked/appreciated your feedback, but we didn't get it changed before you merged._
_Thank you for your quick responses, and good advice. ;-)_
=> chore: Incorporate ST feedback

cores/arduino/stm32/usb/hid/usbd_hid_composite.c, libraries/Keyboard/src/Keyboard.h
Summary:
Adds F13 to F24 to USB HID, make it possible to use KEY F13 to F24 on USB HID keyboard.
```
#include <Keyboard.h>
void setup() {
Keyboard.begin();
}
void loop() {
Keyboard.press(KEY_F13);
delay(100);
Keyboard.release(KEY_F13);   
delay(1000);
}
```
=> Added F13-F24 to USB HID.

boards.txt
Fixes #1849
Adds DIS_U585AI to the list of mass storage names for the discovery board B-U585I-IOT02A.
=> Add mass storage name for B-U585I-IOT02A board

boards.txt, variants/STM32F4xx/F413Z(G-H)(J-T)_F423ZH(J-T)/generic_clock.c, variants/STM32F4xx/F413Z(G-H)(J-T)_F423ZH(J-T)/variant_NUCLEO_F413ZH.cpp, variants/STM32F4xx/F413Z(G-H)(J-T)_F423ZH(J-T)/variant_NUCLEO_F413ZH.h
Add Nucleo F413ZH board
Tested:
- Serial
- SPI
- USB
Fixes #1850
=> Add nucleo f413zh variant

.github/workflows/CodeSpell.yml, .github/workflows/Continuous-Integration.yml, .github/workflows/astyle.yml, CI/astyle/astyle.py
- Harden `astyle.py`
- codespell: use checkout main to remove deprecated warning about deprecated Node.js 12 actions
- made astyle check standalone workflow
=> ci: review

libraries/Wire/src/Wire.cpp, libraries/Wire/src/Wire.h
**Summary**
This allow to have TwoWire callbacks methods inside classes. You can use std::bind to wrap the callback functions.
This is an example of a Class that completely handle the I2C comunication without having the user to manually implement the callbacks:
```cpp
/*
* Lib Functions
*/
I2Client::I2Client(TwoWire *bus)
{
this->_bus = bus;
}
bool I2Client::begin(uint8_t baseAddress)
{
_bus->begin(baseAddress);
_bus->onRequest(std::bind(&I2Client::onHandleRequest, this));
return true;
}
void I2Client::onHandleRequest()
{
_bus->write("hello\n");
}
/*
* Library Usage (main.cpp)
*/
#include <Arduino.h>
#include <Wire.h>
TwoWire bus(PB9, PB8);
I2Client client(&bus);
void setup()
{
client.begin(0x4E); // join i2c bus on address 0x4E
} …
```
=> I2C slave: allow function wrapped callbacks

cores/arduino/HardwareSerial.cpp
Linked to https://www.stm32duino.com/viewtopic.php?p=11204#p11204
=> fix(serial): use defined pins when not mapped on Serial

variants/STM32F4xx/F446R(C-E)T/variant_NUCLEO_F446RE.cpp
This prevents to reset the RTC backup domain when clock source is not the same and a poweroff with VBAT or software reset occurs. Moreover, LSI does not count when power off and VBAT so it is not useful.
Fixes #1919
Board: Nucleo F446RE with SB45 removed. Then connect external 3.3V to VBAT.
```C++
#include <STM32RTC.h>
/* Get the rtc object */
STM32RTC& rtc = STM32RTC::getInstance();
/* Change these values to set the current initial time
format: date: "Dec 31 2017" and time: "23:59:56"
by default use built date and time
*/
static const char* mydate = __DATE__;
static const char* mytime = __TIME__;
//static const char* mydate = "Dec 31 2017";
//static const char* mytime = "23:59:56";
static byte seconds = 0;
static byte minutes = 0;
static byte hours = 0;
static uint32_t subSeconds = 0; …
```
=> fix: remove RTC clock source selection for Nucleo_F446

variants/STM32G0xx/G0B1C(B-C-E)(T-U)_G0C1C(C-E)(T-U)/variant_EBB42_V1_1.h
**Summary**
Mapped LED_BUILTIN to PA13, the onboard blue LED. Was mapped to PNUM_NOT_DEFINED.
LED_BUILTIN works as expected
**motivation**
LED_BUILTIN was mapped to PNUM_NOT_DEFINED. Referencing it would not throw a compile-time error, leading to confusion. 
**Validation**
* CI built without warnings.
* standard Blink example now causes blue LED to blink
Trival edit
No issues raised (easier to fix than raise an issue).
=> map LED_BUILTIN to PA13

cores/arduino/stm32/usb/usbd_conf.h, variants/STM32H7xx/H723Z(E-G)T_H730ZBT_H733ZGT/generic_clock.c, variants/STM32H7xx/H723Z(E-G)T_H730ZBT_H733ZGT/variant_NUCLEO_H723ZG.cpp
=> fix: USB configuration STM32H723ZG

README.md
**Summary**
Fix useless, confusing, and potentially malicious links for "WeAct MiniSTM32H7*" boards.
CC: @ag88
Explain the **motivation** for making this change. What existing problem does the pull request solve?
The previous links lead through a GitHub username change redirect to a repository that appears to be used to demonstrate a security vulnerability.
I replaced them with links to the repo under the WeActStudio GitHub account which actually contains information about the hardware. The other links for WeAct hardware in the readme are under that GitHub and the product listings under the "WeAct Studio Official Store" on AliExpress.
**Validation**
1. Open the previous link:
https://github.com/WeActTC/MiniSTM32H7xx
1. Note that …
=> Fix links for "WeAct MiniSTM32H7*" boards

boards.txt
**Summary**
This PR fixes the upload issue foe some old NUCLEO-F401RE boards
**Motivation**
Some users have NUCLEO-F401RE boards that are seen in the PC as "NUCLEO" mass storage disk
**Validation**
NA
NA
NA
=> Fix issue on upload for old NUCLEO-F401RE boards

libraries/SrcWrapper/src/stm32/hw_config.c
when assert feature is enabled.
Default value (0) is not correct.
Issue raised on the forum:
https://www.stm32duino.com/viewtopic.php?t=1864
/CC @cparata
=> fix(CRC): explicitly set InputDataFormat to avoid assert

.github/workflows/MarkdwonLinksCheck.yml, README.md, variants/STM32MP1xx/MP153AAC_MP153CAC_MP153DAC_MP153FAC_MP157AAC_MP157CAC_MP157DAC_MP157FAC/README.md
Checks  markdown for broken links. 
Using https://github.com/marketplace/actions/linkinator
=> ci: deploy check on Markdown links

variants/STM32L4xx/L4R5Z(G-I)Y_L4R9Z(G-I)Y_L4S5ZIY_L4S9ZIY/variant_SWAN_R5.cpp
Increase drive strength of 32kHz external crystal, in line with calculations specified in ST AN2867 sections 3.3, 3.4, and STM32L4 datasheet DS12023 Table 58. LSE oscillator characteristics.
=> swan_r5: Increase LSE drive strength

cores/arduino/HardwareSerial.cpp
when USB CDC enabled and generic Serial
```
In member function 'void HardwareSerial::setRx(uint32_t)',
inlined from 'HardwareSerial::HardwareSerial(void*, HalfDuplexMode_t)' at C:\Users\<user>\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.5.0-dev\cores\arduino\HardwareSerial.cpp:137:10:
C:\Users\<user>\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.5.0-dev\cores\arduino\HardwareSerial.cpp:573:18: warning: array subscript 'HardwareSerial[0]' is partly outside array bounds of 'USBSerial [1]' [-Warray-bounds]
573 |   _serial.pin_rx = digitalPinToPinName(_rx);
In file included from C:\Users\<user>\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.5.0-dev\cores\arduino\WSerial.h:6,
from …
```
=> fix(serial): warning Warray-bounds

cmake/FindArduinoCtags.cmake, cmake/ensure_core_deps.cmake
CMake 3.24 introduced a change in behavior in ExternalProject_Add() regarding timestamps when extracting an archive.
As updating the code would break compatibility with older CMake versions, this commit instead tells newer CMake versions to behave like older ones, using a policy setting.
Note from the CMake docs:
The OLD behavior of a policy is deprecated by definition and may be removed in a future version of CMake.
-> so the code will have to be updated eventually, and compatibility be broken...
=> fix: silence the warnings from ExternalProject_Add

CI/update/stm32variant.py, platform.txt, system/extras/postbuild.sh, variants/STM32F0xx/openocd.cfg, variants/STM32F1xx/openocd.cfg, variants/STM32F2xx/openocd.cfg, variants/STM32F3xx/openocd.cfg, variants/STM32F4xx/openocd.cfg, variants/STM32F7xx/openocd.cfg, variants/STM32G0xx/openocd.cfg, variants/STM32G4xx/openocd.cfg, variants/STM32H7xx/openocd.cfg, variants/STM32L0xx/openocd.cfg, variants/STM32L1xx/openocd.cfg, variants/STM32L4xx/openocd.cfg, variants/STM32L5xx/openocd.cfg, variants/STM32MP1xx/openocd.cfg, variants/STM32U5xx/openocd.cfg, variants/STM32WBxx/openocd.cfg, variants/STM32WLxx/openocd.cfg
**Summary**
This PR implements the debug feature in Arduino 2.0
**Limitations**
Doesn't work if selected board is a Nucleo-* due to https://github.com/arduino/arduino-ide/issues/1960
Only use with Generic STM32xx series for the moment.
Fixes #1896
=> Add debug openocd

boards.txt, platform.txt
Linked to https://github.com/stm32duino/Arduino_Tools/pull/90
Thanks this PR, it is now possible to flash at specific offset using STM32CubeProgrammer upload method.
Then start at the specified address.
Using `boards.local.txt` feature:
https://arduino.github.io/arduino-cli/latest/platform-specification/#boardslocaltxt
For example to flash at 0x08002000 the Generic STM32F103C8T, define the offset like this:
`GenF1.menu.pnum.GENERIC_F103C8TX.build.flash_offset=0x2000`
Then,
```
stm32CubeProg.sh 0 Blink.ino.bin 0x2000 -g
-------------------------------------------------------------------
STM32CubeProgrammer v2.13.0                  
-------------------------------------------------------------------
ST-LINK SN  : 0023003E3137510539383538
ST-LINK FW  : V3J10M3B5S1
Board       : STLINK-V3SET …
```
=> feat: add offset option to stm32CubeProg upload method

boards.txt, variants/STM32WLxx/WL54CCU_WL55CCU_WLE4C(8-B-C)U_WLE5C(8-B-C)U/variant_GENERIC_NODE_SE_TTI.cpp
LSE was not initialized preventing STM32LoRaWAN usage (RTC init failed)
=> GNSE clock config update and moved to LoRa menu

variants/STM32F4xx/F401R(B-C-D-E)T/variant_NUCLEO_F401RE.cpp
HSE Bypass is available only on MB1136 C-02 (or higher). MB1136 C-01 configured as HSE not used so old clock config does not work for it. Using HSI allows to be compatible with all MB1136 C-0x version.
See https://www.st.com/resource/en/user_manual/um1724-stm32-nucleo64-boards-mb1136-stmicroelectronics.pdf
=> fix(Nucleo_F401RE): use HSI intead of HSE bypass

README.md, boards.txt, variants/STM32WLxx/WL54CCU_WL55CCU_WLE4C(8-B-C)U_WLE5C(8-B-C)U/variant_RAK3172_MODULE.cpp, variants/STM32WLxx/WL54CCU_WL55CCU_WLE4C(8-B-C)U_WLE5C(8-B-C)U/variant_RAK3172_MODULE.h
**Summary**
This PR implements RAK3172 module bases on STM32WLE5CCU
As discussed the LoRaWAN repo (https://github.com/stm32duino/STM32LoRaWAN/pull/13) it is cleaner to add it here.  
This is still a draft as I did not update the main Readme because of a question: I created the section `LoRa modules` , but is it correct? If not, should I place it in the `LoRa`  boards instead?
**Validation**
* LoRaWAN works on the module. I did not test the other peripherals like SPI or I2C
=> Add RAK3172 module

boards.txt
On STM32F72x/F73x, RAM size is 256k and not 192k.
See comment in https://github.com/stm32duino/Arduino_Core_STM32/commit/a855f1291c5e54daf7858e1b39a171677aed04ff
=> update ram size for stm32f72x and f73x

cores/arduino/Print.cpp, cores/arduino/Print.h
**Summary**
This PR implements the following methods in Print.h and Print.cpp:
------------------------
**Motivation**
Some of the new MCUs have a limited memory (ex: 32KB for STM32C011D6) and don't have floating point calculation unit, so a simple accelerometer driver ([example](https://github.com/honnet/MXC4005XC)) can take more than 100% of the flash if we don't optimize it a bit (the compilation fails at first).
This PR saves up to 10K by avoiding the compiler to use ARM libs for double calculation subroutines such as  `__aeabi_dsub`, `__aeabi_dadd`, `__aeabi_dmul`, etc.
------------------------
**Validation**
The following command allows listing the heaviest functions after compilation:
`arm-none-eabi-nm --print-size --size-sort --radix=d -l file.elf | tail -n 3`
```
134242369 …
```
=> Add print(float) to save space (VS double).

README.md, boards.txt, cmake/boards_db.cmake, variants/STM32C0xx/C011D6Y_C011F(4-6)(P-U)_C031F(4-6)P/CMakeLists.txt, variants/STM32C0xx/C011D6Y_C011F(4-6)(P-U)_C031F(4-6)P/variant_STM32C0116_DK.cpp, variants/STM32C0xx/C011D6Y_C011F(4-6)(P-U)_C031F(4-6)P/variant_STM32C0116_DK.h
=> variants(C0): add STM32C0116-DK support

system/STM32H7xx/system_stm32h7xx.c, system/STM32WLxx/system_stm32wlxx.c
=> system(H7): allow VECT_TAB_BASE_ADDRESS redefinition

system/STM32H7xx/system_stm32h7xx.c
=> fix(H7): restore DATA_IN_D2_SRAM comment in system source file

.github/actions/pio-build/README.md, .github/actions/pio-build/action.yml, CI/update/stm32wrapper.py, boards.txt, cmake/boards_db.cmake, cmake/templates/boards_db.cmake, libraries/CMSIS_DSP/src/BasicMathFunctions/BasicMathFunctionsF16.c, libraries/CMSIS_DSP/src/BayesFunctions/BayesFunctionsF16.c, libraries/CMSIS_DSP/src/CommonTables/CommonTablesF16.c, libraries/CMSIS_DSP/src/ComplexMathFunctions/ComplexMathFunctionsF16.c, libraries/CMSIS_DSP/src/DistanceFunctions/DistanceFunctionsF16.c, libraries/CMSIS_DSP/src/FastMathFunctions/FastMathFunctionsF16.c, libraries/CMSIS_DSP/src/FilteringFunctions/FilteringFunctionsF16.c, libraries/CMSIS_DSP/src/InterpolationFunctions/InterpolationFunctions.c, libraries/CMSIS_DSP/src/InterpolationFunctions/InterpolationFunctionsF16.c, libraries/CMSIS_DSP/src/MatrixFunctions/MatrixFunctionsF16.c, libraries/CMSIS_DSP/src/QuaternionMathFunctions/QuaternionMathFunctions.c, libraries/CMSIS_DSP/src/SVMFunctions/SVMFunctionsF16.c, libraries/CMSIS_DSP/src/StatisticsFunctions/StatisticsFunctionsF16.c, libraries/CMSIS_DSP/src/SupportFunctions/SupportFunctionsF16.c, libraries/CMSIS_DSP/src/TransformFunctions/TransformFunctionsF16.c, platform.txt, tools/platformio/platformio-build.py
Package available here:
https://github.com/stm32duino/ArduinoModule-CMSIS/releases/tag/5.9.0
Can be tested using dev package index json:
https://github.com/stm32duino/BoardManagerFiles/raw/dev/package_stmicroelectronics_index.json
=> chore: update to CMSIS 5.9.0

boards.txt
New STLink firmware provides "NODE_G031K8" while previous provides "NOD_G031K8".
This fix allows to support both.
This issue was raised on the forum:
https://www.stm32duino.com/viewtopic.php?t=2085
=> fix(Nucleo_G031K8): add new node name

.github/workflows/PIO-build.yml
Since #2099, pio build failed as it does not used the specified CMSIS version.
/cc @valeros
=> chore(pio): disable build

cores/arduino/HardwareSerial.cpp, cores/arduino/HardwareSerial.h, cores/arduino/stm32/uart.h
when called by `end()`.
Default, no timeout (0). When called by `end()`, default timeout is
`TX_TIMEOUT` which can be redefined if needed.
Fixes #2122.
Tested with below sketch on a Nucleo-WL55JC1.
`Serial1` is instantiate with CTS/RTS. With original code, it wait forever while with this PR it continue after `TIMEOUT_TX` expiration.
```C++
HardwareSerial Serial1(PB7, PB6, PB3, PB4);
uint32_t baud_val[] = {
1200,
2400,
4800,
9600,
115200,
250000
};
// the setup routine runs once when you press reset:
void setup() {
// initialize serial communication at 9600 bits per second:
Serial.begin(9600);
}
// the loop routine runs over and over again forever:
void loop() {
for (uint8_t idx = 0; idx < 6; idx++) {
Serial1.end();
Serial.printf("Test %u\n", baud_val[idx]);
Serial1.begin(baud_val[idx]); …
```
=> feat(serial): add timeout support to flush()

README.md, boards.txt, variants/STM32H7xx/H742Z(G-I)T_H743Z(G-I)T_H747A(G-I)I_H747I(G-I)T_H750ZBT_H753ZIT_H757AII_H757IIT/CMakeLists.txt, variants/STM32H7xx/H742Z(G-I)T_H743Z(G-I)T_H747A(G-I)I_H747I(G-I)T_H750ZBT_H753ZIT_H757AII_H757IIT/variant_NUCLEO_H753ZI.cpp, variants/STM32H7xx/H742Z(G-I)T_H743Z(G-I)T_H747A(G-I)I_H747I(G-I)T_H750ZBT_H753ZIT_H757AII_H757IIT/variant_NUCLEO_H753ZI.h
**Summary**
This PR adds the support for [NUCLEO-H753ZI](https://www.st.com/ja/evaluation-tools/nucleo-h753zi.html) board
This board is same to nucleo-h743zi2, as the user manual is [same](https://www.st.com/resource/en/user_manual/um2407-stm32h7-nucleo144-boards-mb1364-stmicroelectronics.pdf).
And the samples in the official Firmware Package are also [same](https://github.com/STMicroelectronics/STM32CubeH7/tree/master/Projects/NUCLEO-H753ZI), so this board has compatibility with nucleo-h743zi2.
I'm not sure which is better, using existing variant file for H743ZI(2) or create a new one for H753ZI.
(In the first commit, I create a new variant file for H753ZI which is copied from H743ZI)
My board will deliver tomorrow. After the delivery, I can run tests but not sure what should be tested …
=> Support for NUCLEO-H753ZI board

tools/platformio/platformio-build.py
This PR updates PlatformIO build script according to the latest changes in the core:
- Updated build flags
- Better formatting
=> Update PlatformIO build script

cores/arduino/HardwareTimer.h, libraries/SrcWrapper/src/HardwareTimer.cpp
Please, Make sure that your PR is not a duplicate.
Search among the [Pull request](https://github.com/stm32duino/Arduino_Core_STM32/pulls) before creating one.
IMPORTANT: Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.
Thanks for submitting a pull request.
Please provide enough information so that others can review your pull request:
**Summary**
This PR implements the following **feature**
- Support for input channel filtering in HardwareTimer
Currently, HardwareTimer sets the input channel filter to none, any time the mode of the timer is set.
This PR enables the input filter to be set along with the mode.
It is possible to enable setting the input filter separately from the mode if wanted.
**Validation**
Tested with a waveform generator …
=> Add support for setting the channel input filter

libraries/Wire/src/Wire.cpp, libraries/Wire/src/Wire.h
add destructor to call end().
Fixes #2142
<details>
<summary>Tested with this example:</summary>
```C++
#include <Wire.h>
#include <malloc.h>
extern "C" char *sbrk(int i);
/* Use linker definition */
extern char _end;
extern char _sdata;
extern char _estack;
extern char _Min_Stack_Size;
static char *ramstart = &_sdata;
static char *ramend = &_estack;
static char *minSP = (char *)(ramend - &_Min_Stack_Size);
void display_mallinfo(void) {
char *heapend = (char *)sbrk(0);
char *stack_ptr = (char *)__get_MSP();
struct mallinfo mi = mallinfo();
Serial.print("Total non-mmapped bytes (arena):       ");
Serial.println(mi.arena);
Serial.print("# of free chunks (ordblks):            ");
Serial.println(mi.ordblks);
Serial.print("# of free fastbin blocks (smblks):     ");
Serial.println(mi.smblks); …
```
=> fix(Wire): avoid memory leaks

cores/arduino/wiring_time.h
Fixes #2129.
#include <chrono>
```C++
void setup() {
Serial.begin(115200);
auto timepoint = std::chrono::steady_clock::now();
Serial.println(std::chrono::duration_cast<std::chrono::milliseconds>(timepoint.time_since_epoch()).count());
}
void loop() {
auto timepoint = std::chrono::steady_clock::now();
Serial.println(std::chrono::duration_cast<std::chrono::milliseconds>(timepoint.time_since_epoch()).count());
delay(1111);
}
```
=> feat: implement weaked _gettimeofday

cores/arduino/stm32/backup.h
Fixes #2152.
Fix also for STM32U5xx.
=> fix(backup): enable RTC clock for TAMP backup registers

cmake/FindArduinoCtags.cmake, cmake/ensure_core_deps.cmake
**Summary**
The policy statements for CMake policy CMP0135 do not have if statements around them.
As a result, if you have a CMake version less than 3.24 CMake will fail
The policies should have an if statement so that versions between 3.21 and 3.24 can be built.
=> Wrap cmake policies in if statements

libraries/SPI/src/utility/spi_com.c
=> fix(SPI): avoid 0 delay when SPI clock > 1MHz

platform.txt
Fixes #2159
See https://arduino.github.io/arduino-cli/0.34/platform-specification/#sketch-debugging-configuration
=> feat: support compiler.optimization_flags for Arduino IDE 2.X

libraries/SubGhz/src/SubGhz.h
Hello, I found this issue in the following CI run for RadioLib: https://github.com/jgromes/RadioLib/actions/runs/6914863886/job/18813152408#step:8:28
**Summary**
This PR fixes unknown SPI mode in SubGHz library (changed in 392469a1dc66448dea543119b7258128b5596a03).
=> Fixed SPI mode enum in SubGHz library

libraries/SubGhz/src/SubGhz.cpp, libraries/SubGhz/src/SubGhz.h
after SPI rework.
#2191 is not enough to fix `SPISettings` of the SubGhz library.
/cc @jgromes
=> fix(SubGhz): SPISettings not properly defined

libraries/Wire/src/Wire.cpp
**Summary**
The constructor doesn't cleanup memory for a wire instance.
Issues could happen, such as wrong initialization.
Example of bad behaviour using a STM32F411 and an APDS9960 sensor:
```C++
#include "Arduino_APDS9960.h"
APDS9960 * apds;
TwoWire * wire;
void setup() {
Serial.begin(115200);
wire=new TwoWire(PB7,PB8);
wire->begin();
apds = new APDS9960(*wire,PC10);
apds->begin();
}
void loop() {
if (apds->proximityAvailable()) {
int value = apds->readProximity();
Serial.println(value);
}
}
```
The bad behaviour is that after turn off and on the board, wire locks.
Note: it works if you go from boot mode to running mode
This pull request solve this issue adding the following line in TwoWire constructors.
```C++ …
```
=> Fixed memory on Wire instance

variants/STM32F7xx/F722Z(C-E)T_F732ZET/variant_NUCLEO_F722ZE.h
=> fix(nucleo_f722ze): remove duplicate PE2 definition

libraries/SPI/README.md, libraries/SPI/src/SPI.cpp, libraries/SPI/src/SPI.h, libraries/SPI/src/utility/spi_com.c, libraries/SPI/src/utility/spi_com.h
Fixes #2205
For ref: https://github.com/arduino/ArduinoCore-API/discussions/189
Tested with SdFat  patched with:
```patch
index 8b7da94..296a752 100644
@@ -44,9 +44,13 @@ void SdSpiArduinoDriver::end() { m_spi->end(); }
uint8_t SdSpiArduinoDriver::receive() { return m_spi->transfer(0XFF); }
//------------------------------------------------------------------------------
uint8_t SdSpiArduinoDriver::receive(uint8_t* buf, size_t count) {
+#if defined(STM32_CORE_VERSION) && STM32_CORE_VERSION > 0x02070000
+  m_spi->transfer(NULL, buf, count);
+#else
// Must send 0XFF - SD looks at send data for command.
memset(buf, 0XFF, count);
m_spi->transfer(buf, count);
+#endif
return 0;
}
//------------------------------------------------------------------------------
@@ -57,9 +61,17 @@ void …
```
=> feat(spi): add transfer api with tx and rx buffer

cores/arduino/stm32/usb/usbd_desc.c, platform.txt
USB device VID and PID can be defined thanks:
- `boards.txt`: `*.build.vid` or `*.build.pid`
- `build_opt.h`: define `CUSTOM_USBD_VID` or `CUSTOM_USBD_PID`
Else if not defined or specified, default to the ST VID, with PID assigned to HID or CDC devices.
> [!Note]
> if value is specified in the `boards.txt` then `CUSTOM_USBD_*` is ignored.
Fixes #2215
=> feat(usb): allow USB PID to be 0x0000

libraries/Wire/src/utility/twi.c
prevent consumption before entering in low power mode
=> fix(wire): reset pins to INPUT_ANALOG when deinit

platform.txt
Introduced by #2184.
Fixes #2244.
Even if not reproduced, the recipe is not coherent. Only impact Arduino 1.8.x.
=> fix(platform): wrong optimization_flags for Arduino 1.8.x

libraries/Wire/src/utility/twi.c
when all I2C timings are defined
=> fix(i2c): prevent unused variable and functions

cores/arduino/HardwareSerial.cpp, cores/arduino/HardwareSerial.h
This PR addresses the following **bugs/features**
The base class Print [defines `void flush()`](https://github.com/ilolis/Arduino_Core_STM32/blob/dce241d8ebb6affce38adbeebf34eb6372cfbe9b/cores/arduino/Print.h#L103), while the derivative HardwareSerial[ defines `void flush(uint32_t timeout = 0)`](https://github.com/stm32duino/Arduino_Core_STM32/blob/1863c25025441c8c6dbcea5b8ed496db21c12785/cores/arduino/HardwareSerial.h#L128). The issue was that when using the base class instance pointer, the virtual function of the derivative was not being called. This PR resolves this. 
I might be missing something since I am new to this project, so please feel free to correct me :)
=> HardwareSerial's flush() method to override the method of the base class Print

libraries/SrcWrapper/src/HardwareTimer.cpp
This PR fixes a compiler warning when compiling with `-O3`. There's no bounds check in `pauseChannel`, which causes this warning. Adding the bounds check fixes the warning.
```
framework-arduinoststm32\libraries\SrcWrapper\src\HardwareTimer.cpp: In member function 'void HardwareTimer::pauseChannel(uint32_t)':
framework-arduinoststm32\libraries\SrcWrapper\src\HardwareTimer.cpp:203:31: warning: array subscript 4 is above array bounds of 'TimerModes_t [4]' [-Warray-bounds]
203 |   if (_ChannelMode[channel - 1] == TIMER_INPUT_FREQ_DUTY_MEASUREMENT) {
|       ~~~~~~~~~~~~~~~~~~~~~~~~^
In file included from framework-arduinoststm32\cores\arduino\stm32/analog.h:45,
from framework-arduinoststm32\cores\arduino/board.h:8,
from framework-arduinoststm32\cores\arduino/wiring.h:40,
from …
```
=> Fix compiler warning on HardwareTimer

CI/update/stm32cube.py
New series defined HAL version in header file instead of c source one.
=> ci(stm32cube): update parse version

cmake/build_sketch.cmake, cmake/sketch_preprocess_sources.cmake
**Summary**
Allow CMakeLists.txt files to contain multiple build_sketch() targets.
This PR fixes #2282 
A lot of Arduino library projects will contain multiple example applications that demonstrate the library functionality. It is also common practice on larger embedded applications to have a number of small test programs that test specific parts of the systems so these can be tested in isolation from the overall application code. 
This change means all of the examples and tests can be built together from the top level CMakeList.txt file.
There is a dependency error when _.ino_ files are not in the parent directory of the project that is fixed with this pull request.
=> Multiple sketch support

libraries/SrcWrapper/src/stm32/analog.cpp
**Summary**
This PR implements the following:
Adding an option to disable DAC output buffer
**How to use**
DAC output buffer can be disabled by defining the `DISABLE_DAC_OUTPUTBUFFER` using `build_opt.h` or the `hal_conf_extra.h`
=> Adding an option to disable DAC output buffer

libraries/Servo/src/stm32/Servo.cpp
**Summary**
The call to function Servo::write() in Servo::attach() must be done after Servo::min and Servo::max are configured - Servo::write() uses the min/max for mapping the passed value if the value is passed in degrees. Therefore if inital value in attach is set in degress and min/max is not configured when call to Servo::write() is done, the mapping will not be correct.
Fixes: #2308
=> Fix issue with writing inital servo value before min/max is configured

cores/arduino/IPAddress.cpp, cores/arduino/IPAddress.h
This PR implements  the following **features**
Enhancement [IPAddress is missing the toString function interface？](https://github.com/stm32duino/Arduino_Core_STM32/issues/2303)
=> add "toString" function with IPAddress

platform.txt, system/extras/postbuild.sh, system/extras/prebuild.sh
Avoid error when a version or a path is changed.
=> refactor(platform): factorize using variables

cores/arduino/stm32/backup.h
BKPREG1 do not exist anymore, include the correct ll header.
=> fix(backup): update to support STM32C0xx

.github/workflows/MarkdwonLinksCheck.yml, README.md, boards.txt, cmake/boards_db.cmake, variants/STM32WLxx/WL54JCI_WL55JCI_WLE4J(8-B-C)I_WLE5J(8-B-C)I/CMakeLists.txt, variants/STM32WLxx/WL54JCI_WL55JCI_WLE4J(8-B-C)I_WLE5J(8-B-C)I/PeripheralPins_ELV_BM_TRX1.c, variants/STM32WLxx/WL54JCI_WL55JCI_WLE4J(8-B-C)I_WLE5J(8-B-C)I/variant_ELV_BM_TRX1.cpp, variants/STM32WLxx/WL54JCI_WL55JCI_WLE4J(8-B-C)I_WLE5J(8-B-C)I/variant_ELV_BM_TRX1.h
The ELV Modular System is a great fit for the stm32duino library
**Validation**
Github Actions have passed, a working sketch is 
```
#include "STM32LowPower.h"
void setup() {
pinMode(LED_BUILTIN, OUTPUT);
// Configure low power
LowPower.begin();
}
void loop() {
digitalWrite(LED_BUILTIN, HIGH);
LowPower.deepSleep(1000);
digitalWrite(LED_BUILTIN, LOW);
LowPower.deepSleep(1000);
}
```
=> Added Support for ELV-BM-TRX1

CI/codespell/.codespellignore
socio-economic: see https://github.com/codespell-project/codespell/pull/3353 for
shiftIN is a function name so safe to ignore.
=> fix(codespell): ignore new words

CI/update/templates/system_stm32yyxx.c, cmake/set_base_arduino_config.cmake, cores/arduino/stm32/stm32_def.h, libraries/SrcWrapper/src/stm32/system_stm32yyxx.c, platform.txt, tools/platformio/platformio-build.py
this ensure to have the same behavior each time stm32yyxx.h is included.
=> chore(system): define USE_HAL_DRIVER on command line

cores/arduino/stm32/stm32_assert.h, cores/arduino/stm32/stm32_def.h, libraries/SrcWrapper/src/stm32/stm32_def.c
=> feat: support stm32 assert

boards.txt
=> fix: ELV_Modular_System upload options

boards.txt, platform.txt
=> fix(upload_vid): wrong definitions

libraries/USBDevice/src/usbd_ep_conf.c
[Bug]
When using the debug mode, halting the CPU at a breakpoint can create a condition where the HAL USB state machine encounters an off-by-one error in the packet handling. This error is un-recoverable. completely breaks USB communications, and requires you to reset the STM32.
This is caused by an issue with the double-buffering option available in the endpoint hardware.
[Fix] 
Adding the option to disable double buffer mode, and to allow single buffer mode, fixes this issue, and, in my tests, also improves reliability in USB communication with noisy systems, such as motor controllers.
Single buffer mode can now be enabled with -DUSBD_CDC_USE_SINGLE_BUFFER at compile time. 
[Breaking: None] 
This commit does not break any …
=> Add single buffer mode option to USB CDC to fix off-by-one corruption

libraries/Wire/src/Wire.cpp
**Summary**
This PR fixes the memory leak bug caused by multiple Wire.begin() calls, mentioned in #2441
The strategy used here is to initialise the buffer variables on the Wire object initialisation instead of the begin.
**Validation**
* Ran the example code in #2441, now allocateRxBuffer() is only called once at the first call of recieveFrom() and the memory leak has been fixed
* Ensure AStyle check is passed thanks CI
Fixes #2441
=> Fix Wire memory leak

platform.txt
due to {runtime.platform.path} usage when other platform reference the core.
- {runtime.platform.path}:
The absolute path of the board platform folder (i.e. the folder containing boards.txt)
- {build.core.path}:
The path to the selected board's core folder (inside the  core platform, for example hardware/STMicroelectronics/stm32/core/arduino)
Ref:
https://arduino.github.io/arduino-cli/1.0/platform-specification/#referencing-another-core-variant-or-tool
Fixes #2445
=> fix(platform): core reference broken

boards.txt, cmake/scripts/update_boarddb.py, platform.txt
this avoids to add them to `boards.txt` if not needed.
cmake updated to get the default value from `platform.txt`.
/cc @massonal 
This fixes this:
https://github.com/stm32duino/Arduino_Core_STM32/issues/2445#issuecomment-2231956589
=> fix(platform.txt): add default vid/pid definition

tools/platformio/platformio-build.py
One last change that's not synchronized in this repo is the `USBDevice` library not compiled automatically if a USB macro is present. This PR fixes this behavior.
Thanks!
=> Sync PlatformIO build script

libraries/Wire/src/Wire.cpp, libraries/Wire/src/utility/twi.c, libraries/Wire/src/utility/twi.h
Arduino does not support 10 bits addressing mode.
The API is limited to an `uint8_t` address:
https://github.com/arduino/ArduinoCore-API/blob/4a02bfc0a924e1fec34c3bb82ffd5dfba7643a0c/api/HardwareI2C.h#L31
https://github.com/arduino/ArduinoCore-API/blob/4a02bfc0a924e1fec34c3bb82ffd5dfba7643a0c/api/HardwareI2C.h#L36
About the hack to use 10 bits on Arduino:
> Normally on arduino, you can communicate with this device simply by doing something like this:
> 
> ```C++
> Wire.begin(0x79);
> Wire.write(0x08);
> //insert additional communication here
> Wire.endTransmission()
> ```
> However, when using the same code on STM32Duino this communication won't succeed.
> First of all, 0xF2 (0x79 << 1) byte will appear twice on the bus (because we are configuring HAL's I2C interface in 7bit mode, however …
=> fix(wire): support only 7 bits addressing mode

.github/PULL_REQUEST_TEMPLATE.md, cores/arduino/HardwareSerial.h
**Summary**
Removes an atomicity warning in `HardwareSerial.h` that does not apply to (32-bit) STM32. Based on a review on [this response](https://stackoverflow.com/a/52785864/471839) and my own testing, I'm convinced that the atomicity warning and link to an ArduinoCore-avr issue is not relevant.
=> Remove atomicity warning that does not apply to STM32

variants/STM32H5xx/H563Z(G-I)T_H573ZIT/generic_clock.c, variants/STM32H5xx/H563Z(G-I)T_H573ZIT/variant_NUCLEO_H563ZI.cpp
Please, Make sure that your PR is not a duplicate.
Search among the [Pull request](https://github.com/stm32duino/Arduino_Core_STM32/pulls) before creating one.
IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/stm32duino/Arduino_Core_STM32/blob/main/CONTRIBUTING.md) file for detailed contributing guidelines.
Thanks for submitting a pull request.
Please provide enough information so that others can review your pull request:
**Summary**
- There were no plans to change LPUART, but since it will be lower than current value when I fix ADC/DAC problem, I changed it as described in #2505.
- By setting `SRC / M = 2` `N = 250` for PLL1/2/3 you can flexibly determine clock source frequency and easily calculate division P/Q/R. …
=> Fix H563ZI clock config.

libraries/SrcWrapper/src/stm32/analog.cpp
=> fix(h5): disable cache during DAC channel configuration

variants/STM32H5xx/H503KBU/generic_clock.c, variants/STM32H5xx/H503RBT/generic_clock.c, variants/STM32H5xx/H503RBT/variant_NUCLEO_H503RB.cpp, variants/STM32H5xx/H563R(G-I)T_H573RIT/generic_clock.c
Basically same as "Optimize PLL ratio" in #2506.
**Summary**
By setting `SRC / M = 2` `N = 250` for PLL1/2/3 you can flexibly determine clock source frequency and easily calculate division P/Q/R.
<details>
<summary>CubeMX Screenshots</summary>
- for H503KB/H503RB
- for H573RI
</details>
=> Optimize H573RI/H503KB/H503RB clock config.

boards.txt
to be aligned with vid.0.
Fixes #2511.
=> fix(boards.txt): use pid.0 instead of pid for Blues Cygnet

boards.txt, platform.txt
- Modified `platform.txt` to enable programming via OpenOCD, which was already used for debugging.
- Added an example demonstrating how to program all Nucleo-64 boards, whether they use STLink or DAPLink.
To avoid conflict, the support for STeaMi will be added after the merge of the PR #2526
*Benefits:*
- Enables programming of STeaMi boards.
- Supports P_NUCLEO boards that use DAPLink instead of STLink to leverage WebUSB functionality.
=> feat(platform): Add OpenOCD programming support (STlink and DAP)

boards.txt
**Summary**
This PR implements the support for using a STM32CubeProgrammer with a J-Link from the Arduino IDE
Explain the **motivation** for making this change. What existing problem does the pull request solve?
I have a J-Link probe and can use it directly in STM32CubeProgrammer, but not in the Arduino IDE
**Validation**
I tested it and it works, doesn't seem to break anything else.
close #2452
=> J-Link Support for STM32F1

libraries/Wire/src/utility/twi.c
=> fix(i2c): wrong clock frequencies for I2C5 and I2C6

libraries/SPI/src/SPI.cpp, libraries/SPI/src/SPI.h
Fixes #2543 
`SPIClass` constructor was factorized.
=> fix(spi): ensure spi_t structure properly init

boards.txt, variants/STM32C0xx/C071R(8-B)T/generic_clock.c, variants/STM32C0xx/C071R(8-B)T/variant_NUCLEO_C071RB.cpp
Enable the HSI48 for USB (not done thanks CubeMX code generation). Add GenC0 USB menu.
Moved G0 one in alphabetical order.
Fixes #2582.
Tested with Nucleo C071RB.
=> chore(c0): enable usb

boards.txt
**Summary**
This PR implements the following **feature**
Black Magic Debug Probe supports interactive debugging as well as one-shot uploading, via gdb script or multi-argument command line. This is useful with Generic boards which often don't have an onboard debugger. Method was contributed here earlier and carried on for GenF1, GenF3, GenF4, GenL0, GenFlight.
Let's extend this to 3rd party boards, too. Garatronic Pybstick26 was omitted because it only has LEDs on PA13/14 SWD, no testpoints even.
Of course I am unsure about allowing this on Nucleo/Disco/Eval products from ST, which should have a working STLink/V2 or V3E running proprietary firmware; but also P1x6 SWD 2.54mm or STDC-14 headers. If you deem this okay, then it's +20 more lines in a third commit.
BMDA does not create a COM …
=> feat(platform): extend Black Magic Debug Probe upload method to more boards

cores/arduino/wiring_digital.c
Penalty for the check should be a single instruction for pin numbers below NUM_DIGITAL_PINS, 9 for pin numbers between PNUM_ANALOG_BASE and NUM_ANALOG_INTERNAL_FIRST.
Tests done on a Black F407VE board
Fixes #2612
=> Fix dead lock with pin above NUM_DIGITAL_PINS

libraries/SrcWrapper/src/stm32/hw_config.c
if it is not defined.
Configure the system power supply according to the definition to be used at compilation preprocessing level.
The application shall set one of the following configuration option:
- USE_PWR_LDO_SUPPLY
- USE_PWR_DIRECT_SMPS_SUPPLY
- USE_PWR_EXTERNAL_SOURCE_SUPPLY
- USE_PWR_SMPS_1V8_SUPPLIES_LDO
- USE_PWR_SMPS_2V5_SUPPLIES_LDO
- USE_PWR_SMPS_1V8_SUPPLIES_EXT_AND_LDO
- USE_PWR_SMPS_2V5_SUPPLIES_EXT_AND_LDO
- USE_PWR_SMPS_1V8_SUPPLIES_EXT
- USE_PWR_SMPS_2V5_SUPPLIES_EXT
=> feat(h7): add a message for the system power supply

variants/STM32H5xx/H503CB(T-U)/generic_clock.c, variants/STM32H5xx/H503RBT/generic_clock.c, variants/STM32H5xx/H503RBT/variant_NUCLEO_H503RB.cpp, variants/STM32H5xx/H562R(G-I)T/generic_clock.c, variants/STM32H5xx/H562R(G-I)T/variant_WEACT_H562RG.cpp, variants/STM32H5xx/H563IIKxQ_H573IIKxQ/generic_clock.c, variants/STM32H5xx/H563IIKxQ_H573IIKxQ/variant_STM32H573I_DK.cpp, variants/STM32H5xx/H563R(G-I)T_H573RIT/generic_clock.c, variants/STM32H5xx/H563Z(G-I)T_H573ZIT/generic_clock.c, variants/STM32H5xx/H563Z(G-I)T_H573ZIT/variant_NUCLEO_H563ZI.cpp
SPI clock selection have to be explicitly done and ensure frequency allows standard SPI freq based on the SPI baudrate prescaler.
Also prevent to use HSE as it is not operational
as oscillator. See Errata sheet.
Fixes #2598
=> fix(h5): review system clock configuration

libraries/SrcWrapper/src/stm32/uart.c
This enables UART Tx and Rx pin swap function on STM32 families that support it (F0, L0, L4, G0, G4, H7 etc.) 
In order to enable pin swap, user just needs to _swap the pins_ either when declaring `HardwareSerial` object:
```cpp
//                      RX    TX
HardwareSerial Serial1(PA10, PA9); // uses normal pins
//                      RX    TX
HardwareSerial Serial1(PA9, PA10); // uses swapped pins
```
or by using `setTx()` and `setRx()` methods:
```cpp
Serial1.setRx(PA9);  // normally it is a Tx pin
Serial1.setTx(PA10); // normally it is a Rx pin
Serial1.begin(9600);
```
If the chip does not support the swap, or the pins are incorrect, the library behaves the same way as before (throws an error for invalid pins).
The cool thing is that it even supports half-duplex mode on the …
=> feat(uart): support UART Tx Rx pin swap function

libraries/SrcWrapper/src/stm32/uart.c
STM32H5 have those instances.
Fixes #2640.
=> fix(uart): add missing USART11 and UART12 support

variants/STM32G4xx/G431C(6-8-B)U_G441CBU/variant_B_G431B_ESC1.h
HSE was set to 24MHz instead of 8MHz, and was overriding anything else trying to set the HSE speed, causing 1ms to be 3ms. Changing it here fixes everything.
See https://www.st.com/en/evaluation-tools/b-g431b-esc1.html#cad-resources, mb1419-g431cbu6-b01, Crystal is 8MHz in schematic.
=> Update wrong HSE value on variant_B_G431B_ESC1.h

libraries/SrcWrapper/src/stm32/uart.c
=> chore(uart): set LSE as source only if LSE is ready

boards.txt, debugger/select_dapdirect.cfg, platform.txt, variants/STM32C0xx/C011J(4-6)M/generic_clock.c
* update to [xpack arm-none-eabi-gcc v14.2.1-1.1](https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases/tag/v14.2.1-1.1)
* update to [xpack-openocd v0.12.0-6](https://github.com/xpack-dev-tools/openocd-xpack/releases/tag/v0.12.0-6)
* add dapdirect_swd
=> chore: xpack update

boards.txt, platform.txt
hla_swd deprecated since STLink V2 (2015).
https://openocd.org/doc/html/Debug-Adapter-Configuration.html#SWD-Transport
> Unless your adapter uses either [the hla interface driver](https://openocd.org/doc/html/Debug-Adapter-Configuration.html#hla_005finterface) (in which case the command is transport select hla_swd) or [the st-link interface driver](https://openocd.org/doc/html/Debug-Adapter-Configuration.html#st_005flink_005fdap_005finterface) (in which case the command is transport select dapdirect_swd).
https://openocd.org/doc/html/Debug-Adapter-Configuration.html#st_005flink_005fdap_005finterface
> This is a driver that supports STMicroelectronics adapters ST-LINK/V2 (from 2015 firmware V2J24), STLINK-V3 and STLINK-V3PWR, thanks to a new API that provides directly access the arm ADIv5 …
=> feat(debugger): set dapdirect_swd as default transport

system/Drivers/STM32C0xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h, system/Drivers/STM32C0xx_HAL_Driver/Inc/stm32c0xx_ll_usart.h, system/Drivers/STM32C0xx_HAL_Driver/Release_Notes.html, system/Drivers/STM32C0xx_HAL_Driver/Src/stm32c0xx_hal.c, system/Drivers/STM32C0xx_HAL_Driver/Src/stm32c0xx_hal_adc_ex.c, system/Drivers/STM32C0xx_HAL_Driver/Src/stm32c0xx_hal_rcc.c, system/Drivers/STM32C0xx_HAL_Driver/Src/stm32c0xx_hal_tim.c, system/Drivers/STM32C0xx_HAL_Driver/Src/stm32c0xx_hal_uart.c, system/Drivers/STM32C0xx_HAL_Driver/Src/stm32c0xx_hal_uart_ex.c, system/Drivers/STM32YYxx_HAL_Driver_version.md
* From [STM32CubeC0 v1.4.0](https://github.com/STMicroelectronics/STM32CubeC0/releases/tag/v1.4.0)
* Update HAL from version 1.3.0 to 1.4.0
=> system(c0) update STM32C0xx HAL Drivers to v1.4.0

platform.txt
https://github.com/xpack-dev-tools/openocd-xpack/releases/tag/v0.12.0-6
Fixes #2683.
When deploying xpack-openocd v0.12.0-5 issue was found in openocd:
https://github.com/xpack-dev-tools/openocd-xpack/issues/34
A new version was released xpack-openocd v0.12.0-6 with the fix.
Unfortunately when testing it the platform.txt updated was not committed. As xpack-openocd v0.12.0-5 was always installed no issue was seen.
=> fix(openocd): update to xpack-openocd v0.12.0-6

variants/STM32F7xx/F765V(G-I)(H-T)_F767V(G-I)(H-T)_F777VI(H-T)/generic_clock.c, variants/STM32F7xx/F765V(G-I)(H-T)_F767V(G-I)(H-T)_F777VI(H-T)/variant_REMRAM_V1.cpp, variants/STM32F7xx/F765Z(G-I)T_F767Z(G-I)T_F777ZIT/generic_clock.c, variants/STM32F7xx/F765Z(G-I)T_F767Z(G-I)T_F777ZIT/variant_NUCLEO_F767ZI.cpp
Fixes #2692.
Also use HSE bypass for Nucleo-F767ZI instead of HSI.
=> fix(f7): PLLR value

variants/STM32H5xx/H503CB(T-U)/generic_clock.c, variants/STM32H5xx/H503KBU/generic_clock.c, variants/STM32H5xx/H503RBT/generic_clock.c, variants/STM32H5xx/H503RBT/variant_NUCLEO_H503RB.cpp, variants/STM32H5xx/H503RBT/variant_NUCLEO_H503RB.h, variants/STM32H5xx/H562R(G-I)T/generic_clock.c, variants/STM32H5xx/H562R(G-I)T/variant_WEACT_H562RG.cpp, variants/STM32H5xx/H562R(G-I)T/variant_WEACT_H562RG.h, variants/STM32H5xx/H563IIKxQ_H573IIKxQ/generic_clock.c, variants/STM32H5xx/H563IIKxQ_H573IIKxQ/variant_STM32H573I_DK.cpp, variants/STM32H5xx/H563R(G-I)T_H573RIT/generic_clock.c, variants/STM32H5xx/H563Z(G-I)T_H573ZIT/generic_clock.c, variants/STM32H5xx/H563Z(G-I)T_H573ZIT/variant_NUCLEO_H563ZI.cpp, variants/STM32H5xx/H563Z(G-I)T_H573ZIT/variant_NUCLEO_H563ZI.h
**Summary**
The generic clock config for STM32H5 series will be made as common as possible.
As a result, only differences will be the number of peripherals that vary by part number, clock source and peripherals used by each variant, etc.
We have also tidied up the writing style, such as commenting out.
This fixes `H503KBU` which was not included in https://github.com/stm32duino/Arduino_Core_STM32/issues/2598 fix.
**Common changes**
- Common to all
- Common in `H503`
- Common in `H562` `H563` `H573`
- `RCC_PERIPHCLK_SPI4` and `RCC_PERIPHCLK_SPI5` is only for models with high pin count.
**Variant-specific changes**
- `H503CB(T-U)`
- `H503KBU`
- `H503RBT`
- variant: `NUCLEO_H503RB`
- `H562R(G-I)T`
- variant: `WEACT_H562RG`
- `H563IIKxQ_H573IIKxQ`
- variant: `STM32H573I_DK`
- `H563R(G-I)T`
- …
=> Tidying up clock config of H5.

cores/arduino/HardwareSerial.cpp, cores/arduino/HardwareSerial.h, libraries/SrcWrapper/inc/uart.h, libraries/SrcWrapper/src/stm32/uart.c
This PR implements the _HardwareSerial_ bool() operator.
Currently, the core blocks if there is a write to a closed _HardwareSerial_ instance. The tx buffer will rapidly be full and the core waits forever for free space.
The bool() operator is a good way to check if the _HardwareSerial_ object is opened and ready to transmit data but in the current implementation, it allways returns true.
The PR implements a complete  bool() operator:
- Returns true when the _HardwareSerial_ object is ready.
- Returns false when the _HardwareSerial_ object is not ready.
Sample code:
```cpp
Serial.begin();
if (Serial) {
Serial.println("Serial is opened");
Serial.flush();
}
Serial.end();
if (Serial) {
Serial.println("Serial is closed. Never be printed");
}
```
=> feat (uart): implement proper operator bool()

libraries/SrcWrapper/src/stm32/uart.c
=> fix(uart): unused warnings

cores/arduino/wiring_analog.c
**Summary**
STM32U5 Series cannot set analog read resolution to 14-bit. Because `MAX_ADC_RESOLUTION` has a value of 12 instead of 14.
This PR fixes the following **bugs**
**Motivation**
When set analog read resolution to 14-bit, analog only read with 12-bit
**Validation**
* Build and test with custom U585VI board
=> Add ADC 14bit support in U5

tools/platformio/platformio-build.py
This PR fixes an issue in the platformio build script where a tuple containing the arguments is placed into LINKFLAGS. This broke a custom script in a different project (Bosch BSEC2 sensor library) that looks at LINKFLAGS.
I'm not sure how it worked before..
I've tested this locally and it's a minor change.
=> Fix LINKFLAGS containing a tuple in platformio build script

libraries/Wire/src/Wire.cpp
**Summary**
Fixed an issue in Wire.begin() where the I2C bus recovery routine was always triggered, even when initializing as a slave device. This could lead to unintended manipulation of the SCL line while SDA is low - potentially during an active transmission from the master. Only the master should perform a bus recovery.
This PR fix ensures that the SCL line is not manipulated when Wire.begin() is called in slave mode.
=> fix(Wire): only recover bus when device is master

variants/STM32F7xx/F765Z(G-I)T_F767Z(G-I)T_F777ZIT/variant_NUCLEO_F767ZI.cpp
This reverts commit 1ef1f862c81257c73d046a957194e3c541653988.
Fixes #2795.
=> Revert "chore(f7): use HSE bypass for Nucleo-F767ZI"

variants/STM32F0xx/F070CBT/startup_Mx00_f070xb.S, variants/STM32F1xx/F103C8T_F103CB(T-U)/startup_M200_f103xb.S
=> fix: add guard to custom startup scripts
