cores/arduino/pins_arduino.c
cores/arduino/pins_arduino.h

Fix #54
Signed-off-by: Frederic.Pillon <frederic.pillon@st.com>

Fix pinNametoDigitalPin issue

---

variants/DISCO_F100RB/variant.cpp

Switch SYSCLK from HSI to HSE.
Replace PR #86

DISCO_F100RB board using HSI should use HSE

---

cores/arduino/stm32/clock.c

Add HAL_SYSTICK_IRQHandler() call, allow use of HAL_SYSTICK_Callback()

---

libraries/Servo/library.properties
libraries/Servo/src/Servo.h
libraries/Servo/src/stm32/Servo.cpp
libraries/Servo/src/stm32/ServoTimers.h

Fix servo pulse width error. #102 
Library reworked to match with [official Arduino library](https://github.com/arduino-libraries/Servo)

Fix servo lib

---

cores/arduino/stm32/spi_com.c
libraries/SPI/src/SPI.cpp

[SPI] Set Handle state only the first time

---

cores/arduino/Arduino.h

Ensure gcc version is at least 6.3

Added checking gcc version

---

variants/DISCO_L475VG_IOT/variant.cpp

PLLM to 6 is not possible with PLLN set to 40.
Fix USB clock to have 48MHz instead of MSI one

[Disco-L475VG] Fix SystemClock_Config

---

cores/arduino/stm32/twi.c

Fix warning in twi.c (I2C)

---

boards.txt

This PR prepares the existing RemRam section to be used as a general "3D printer boards" section.
CC @ktand

Change RemRam section to "3D printer boards" section

---

cores/arduino/avr/dtostrf.c

[dtostrf] Fix missing leading zeros in decimal part

---

cores/arduino/stm32/usb/cdc/usbd_cdc_if.c

By happy coincidence, this error doesn't affect the code. But error is error and must be resolved.

Fix of error

---

.travis.yml
platform.txt

Package available here:
https://github.com/stm32duino/ArduinoModule-CMSIS/releases/tag/5.4.0

Moved from CMSIS 5.3.0 to 5.4.0

---

.travis.yml
platform.txt

Packages available here:
* https://github.com/stm32duino/ArduinoModule-CMSIS/releases/tag/5.5.1
* https://github.com/stm32duino/arm-none-eabi-gcc/releases/tag/8-2018-q4-major

Update CMSIS and arm-none-eabi-gcc

---

cores/arduino/stm32/timer.c
cores/arduino/stm32/timer.h

This PR is based on #447 
* Rebase on top of the master
* Squash several commit
* Update commit message
* Factorize some code
* Fix typo
* Reorder functions
Still Servo to review and maybe could be proposed as PR replacement of https://github.com/arduino-libraries/Servo/pull/10

PR #447 review

---

cores/arduino/wiring_analog.c
cores/arduino/wiring_analog.h

Reference:
https://www.arduino.cc/reference/en/language/functions/analog-io/analogreference/
Same as Arduino SAM Boards (Due)
Fix #403

Add dummy analogReference() for compatibility

---

CI/utils/gen_wrapper.sh

This scripts generates wrapping for:
* HAL/LL c sources
* LL headers
* CMSIS startup
* CMSIS DSP sources

Add scripts to wrap files

---

cores/arduino/stm32/analog.cpp

[ADC] Fix ADC_InitTypeDef member for STM32F37xx

---

libraries/IWatchdog/src/IWatchdog.cpp
libraries/IWatchdog/src/IWatchdog.h

[IWatchdog library] Add license

---

cores/arduino/Arduino.h

See https://github.com/Sloeber/arduino-eclipse-plugin/issues/1143
Thanks @jantje

Add an include to ease Sloeber plugin usage

---

cores/arduino/HardwareTimer.cpp

HardwareTimer: replace comparison with NULL by implicit bool conversion
Like advised in https://github.com/stm32duino/Arduino_Core_STM32/pull/892
Already started in this #892

HardwareTimer: replace comparison with NULL by implicit bool conversion

---

platform.txt

[BMP upload] Fix compiler path

---

cores/arduino/Arduino.h
cores/arduino/main.cpp

Can be defined WEAK or not in the variant
and/or at sketch level.

Fix weaked initVariant()declaration

---

README.md

Updating the MCU used in Prntr Board Vx.

Update Prntr Board device

---

.github/workflows/Continuous-Integration.yml
platform.txt

See https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases/tag/v9.3.1-1.1
See #1111

Moved from arm-none-eabi-gcc 9.2.1-1.1 to 9.3.1-1.1

---

system/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h
system/Drivers/STM32F0xx_HAL_Driver/Inc/stm32f0xx_hal_def.h
system/Drivers/STM32F0xx_HAL_Driver/Inc/stm32f0xx_hal_i2c.h
system/Drivers/STM32F0xx_HAL_Driver/Inc/stm32f0xx_hal_i2c_ex.h
system/Drivers/STM32F0xx_HAL_Driver/Inc/stm32f0xx_hal_pcd.h
system/Drivers/STM32F0xx_HAL_Driver/Inc/stm32f0xx_hal_pcd_ex.h
system/Drivers/STM32F0xx_HAL_Driver/Inc/stm32f0xx_hal_smbus.h
system/Drivers/STM32F0xx_HAL_Driver/Inc/stm32f0xx_ll_gpio.h
system/Drivers/STM32F0xx_HAL_Driver/Inc/stm32f0xx_ll_i2c.h
system/Drivers/STM32F0xx_HAL_Driver/Inc/stm32f0xx_ll_usb.h
system/Drivers/STM32F0xx_HAL_Driver/License.md
system/Drivers/STM32F0xx_HAL_Driver/README.md
system/Drivers/STM32F0xx_HAL_Driver/Release_Notes.html
system/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal.c
system/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_gpio.c
system/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c.c
system/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c_ex.c
system/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pcd.c
system/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pcd_ex.c
system/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_smbus.c
system/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_ll_gpio.c
system/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_ll_usb.c
system/Drivers/STM32YYxx_HAL_Driver_version.md

Update from [STM32CubeF0 FW v1.11.1](https://github.com/STMicroelectronics/STM32CubeF0/releases/tag/v1.11.1):
- HAL Drivers to v1.7.4

Update STM32F0 HAL driver

---

.github/workflows/Continuous-Integration.yml

Will allow to test update in the script (Ex:  #1164)

[CI] Remove platformio-build.py from ignore paths

---

variants/NUCLEO_L053R8/variant.cpp

Enable USB clock for Nucleo L053R8

---

CI/build/arduino-cli.py

"Error during build: fork/exec <...> : no such file or directory"
was not detected.

[CI] Add fork error pattern detection

---

CI/build/arduino-cli.py

~Just for testing.~ Linked to https://github.com/arduino/arduino-cli/issues/759.

[CI] Use --additional-urls for board details

---

variants/PNUCLEO_WB55RG/otp.h
variants/PNUCLEO_WB55RG/variant.cpp
variants/PNUCLEO_WB55RG/variant.h

This PR is the introduction  of the BLE for the stm32WB55 
Requires https://github.com/stm32duino/STM32duinoBLE/pull/17

enabling IPCC module of the stm32WB55

---

cores/arduino/HardwareTimer.cpp

Issue raised by mlundin on the forum:
https://www.stm32duino.com/viewtopic.php?f=38&p=5264#p5264

[HardwareTimer] Fix typo

---

CI/build/arduino-cli.py

New arduino-cli 0.18.0 is not backward compatible.
Json format case issue.

[CI] Fix arduino-cli changes

---

cores/arduino/wiring_analog.c

fix: analog: use MAX_PWM_RESOLUTION instead of MAX_ADC_RESOLUTION

---

README.md
boards.txt
variants/STM32L0xx/L010RBT/variant_NUCLEO_L010RB.cpp
variants/STM32L0xx/L010RBT/variant_NUCLEO_L010RB.h

variant: add Nucleo L010RB

---

.github/workflows/Continuous-Integration.yml

Revert "Temporary disable pio build"

---

variants/STM32L0xx/L051C(6-8)(T-U)/PeripheralPins_RHF76_052.c

fix: variant: correct guard for RHF76_052

---

tools/platformio/boards_remap.json
tools/platformio/platformio-build.py

This PR updates PlatformIO build scripts according to the latest changes in v2.1

Synchronize PlatformIO build scripts

---

CI/update/stm32cube.py

**Summary**
ci(stm32cube): enhance version regex to match RC versions for example

ci(stm32cube): enhance version regex to match RC versions for example

---

tools/platformio/platformio-build.py

Improve support for hand-written asm source files

---

platform.txt

Requires https://github.com/stm32duino/Arduino_Tools/pull/89

chore: unified maple upload method

---

libraries/SrcWrapper/src/stm32/clock.c

chore: prevent old gcc version to raised an error

---

variants/STM32G4xx/G473R(B-C-E)T_G474R(B-C-E)T_G483RET_G484RET/variant_NUCLEO_G474RE.cpp

Issue raised here:
https://www.stm32duino.com/viewtopic.php?t=2182
Also fix LPUART config to be able to use at 9600.

fix(nucleo_G474RE): wrong SystemClock_Config configuration

---

cmake/convert_file.cmake

fix(cmake): remove .elf extension from generated .bin and .hex

---

tools/platformio/platformio-build.py

- This PR updates PR with the latest changes
- Resolves #2479

Sync PlatformIO build script

---

boards.txt

fix: Blues vid/pid couple

---

cores/arduino/Print.cpp

https://github.com/arduino/ArduinoCore-API/issues/178
Fixes #2545

fix: print(0ULL) output nothing

---

platform.txt

https://github.com/xpack-dev-tools/openocd-xpack/releases/tag/v0.12.0-4

chore: update to xpack-openocd v0.12.0-4

---

CI/update/stm32variant.py
boards.txt
variants/STM32H7xx/H725A(E-G)I_H730ABIxQ_H735AGI/boards_entry.txt
variants/STM32H7xx/H725I(E-G)K_H730IBKxQ_H735IGK/boards_entry.txt
variants/STM32H7xx/H725I(E-G)T_H730IBTxQ_H735IGT/boards_entry.txt
variants/STM32H7xx/H7A3A(G-I)IxQ_H7B0ABIxQ_H7B3AIIxQ/boards_entry.txt
variants/STM32H7xx/H7A3I(G-I)KxQ_H7B0IBKxQ_H7B3IIKxQ/boards_entry.txt
variants/STM32H7xx/H7A3I(G-I)TxQ_H7B3IITxQ/boards_entry.txt
variants/STM32H7xx/H7A3L(G-I)HxQ_H7B3LIHxQ/boards_entry.txt
variants/STM32H7xx/H7A3QIYxQ_H7B3QIYxQ/boards_entry.txt
variants/STM32H7xx/H7A3V(G-I)HxQ_H7B3VIHxQ/boards_entry.txt
variants/STM32H7xx/H7A3V(G-I)TxQ_H7B3VITxQ/boards_entry.txt
variants/STM32H7xx/H7A3Z(G-I)TxQ_H7B3ZITxQ/boards_entry.txt
variants/STM32L1xx/L100C6Ux(A)_L151C(6-8-B)(T-U)x(A)_L152C(6-8-B)(T-U)x(A)/boards_entry.txt
variants/STM32L1xx/L100R(8-B)Tx(A)_L151R(6-8-B)Tx(A)_L152R(6-8-B)Tx(A)/boards_entry.txt
variants/STM32L1xx/L151R(6-8-B)Hx(A)_L152R(6-8-B)Hx(A)/boards_entry.txt
variants/STM32L1xx/L151RC(T-Y)x(A)_L151UCY_L152RCTx(A)_L152UCY_L162RCTx(A)/boards_entry.txt
variants/STM32L1xx/L151V(8-B)(H-T)x(A)_L152V(8-B)(H-T)x(A)/boards_entry.txt
variants/STM32L1xx/L151VC(H-T)x(A)_L152VC(H-T)x(A)_L162VC(H-T)x(A)/boards_entry.txt

fix: wrong product lines

---

README.md

fix(doc): typo

---

.github/workflows/MarkdwonLinksCheck.yml
README.md

Also schedule url check each day at 11 AM.

fix: broken url

---

libraries/USBDevice/inc/usbd_conf.h
variants/STM32G0xx/G0B0CET/generic_clock.c
variants/STM32G0xx/G0B0RET/generic_clock.c
variants/STM32G0xx/G0B0VET/generic_clock.c

variant(g0): generic STM32G0B0RET USB clock configuration
